import { useMemo, useState } from 'react'
import { CalendarDays, CheckCircle2, ChevronLeft, Clock, MapPin, Monitor, Stethoscope } from 'lucide-react'
import { useAuth } from '../../lib/AuthContext'
import { getPatientProfessional } from '../../lib/invitations'
import { getProfileByUserId, modeLabels, type AttendanceMode, type ProfessionalService } from '../../lib/professionalProfile'
import { appointmentStatusClass, appointmentStatusLabels, createAppointment, getAvailableSlots, getPatientAppointments } from '../../lib/appointments'

const money = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'})
const dayFormat = new Intl.DateTimeFormat('pt-BR',{weekday:'short',day:'2-digit',month:'short'})
const fullDate = new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})
function nextDates(count=14){ return Array.from({length:count},(_,i)=>{ const d=new Date(); d.setHours(12,0,0,0); d.setDate(d.getDate()+i+1); return d }) }

export function PatientAppointments(){
  const { user } = useAuth(); const relationship = user ? getPatientProfessional(user.id) : null
  const professionalId = relationship?.professional.id || ''; const profile = professionalId ? getProfileByUserId(professionalId) : null
  const [step,setStep] = useState<'list'|'service'|'date'|'confirm'|'success'>('list')
  const [service,setService] = useState<ProfessionalService|null>(null); const [mode,setMode] = useState<AttendanceMode|null>(null)
  const dates = useMemo(()=>nextDates(),[]); const [date,setDate] = useState(''); const [start,setStart] = useState(''); const [note,setNote] = useState(''); const [error,setError] = useState(''); const [,refresh]=useState(0)
  const appointments = user ? getPatientAppointments(user.id) : []
  const slots = service && date ? getAvailableSlots(professionalId,service,date) : []
  function selectService(item:ProfessionalService){ setService(item); setMode(item.modes[0]||null); setStep('date'); setDate(''); setStart('') }
  function submit(){ if(!user||!service||!mode||!date||!start)return; try{ createAppointment({professionalId,patientId:user.id,service,date,start,mode,patientNote:note}); setError(''); setStep('success'); refresh(v=>v+1) }catch(err){ setError(err instanceof Error?err.message:'Não foi possível agendar.') } }
  if(!relationship||!profile) return <div className="card"><h2>Nenhuma profissional vinculada</h2><p className="muted">Você precisa acessar a Rede Maternar por um convite profissional antes de agendar.</p></div>
  return <>
    <div className="topbar"><div><h1>Agendamentos</h1><div className="muted">Escolha um serviço e encontre o melhor horário.</div></div>{step!=='list'&&<button className="btn btn-secondary" onClick={()=>setStep('list')}><ChevronLeft size={17}/> Voltar</button>}</div>
    {step==='list'&&<><div className="card booking-intro"><div><span className="badge">Agenda on-line</span><h2>Agende com {profile.displayName}</h2><p className="muted">Os horários exibidos respeitam a disponibilidade real da profissional.</p></div><button className="btn btn-primary" onClick={()=>setStep('service')}><CalendarDays size={18}/> Novo agendamento</button></div>
    <div className="card" style={{marginTop:18}}><h2>Meus atendimentos</h2>{appointments.length?<div className="appointment-list">{appointments.map(item=><div className="appointment-row" key={item.id}><div className="date-tile"><strong>{item.date.slice(8,10)}</strong><span>{new Date(`${item.date}T12:00:00`).toLocaleDateString('pt-BR',{month:'short'})}</span></div><div className="appointment-main"><strong>{item.serviceName}</strong><span>{item.start} · {modeLabels[item.mode]} · {money.format(item.price)}</span></div><span className={`status-pill ${appointmentStatusClass[item.status]}`}>{appointmentStatusLabels[item.status]}</span></div>)}</div>:<div className="empty-state"><CalendarDays/><h3>Você ainda não tem consultas</h3><p>Seu primeiro agendamento aparecerá aqui.</p></div>}</div></>}
    {step==='service'&&<div className="card"><div className="section-heading"><div><span className="step-label">Etapa 1 de 3</span><h2>Qual atendimento você precisa?</h2></div></div><div className="service-choice-grid">{profile.services.filter(item=>item.active).map(item=><button className="service-choice" key={item.id} onClick={()=>selectService(item)}><div className="service-choice-icon"><Stethoscope/></div><div><h3>{item.name}</h3><p>{item.description}</p><div className="service-choice-meta"><span><Clock size={15}/>{item.durationMinutes} min</span><strong>{money.format(item.price)}</strong></div></div></button>)}</div></div>}
    {step==='date'&&service&&<div className="grid booking-grid"><div className="card"><span className="step-label">Etapa 2 de 3</span><h2>Escolha a data e o horário</h2><div className="date-strip">{dates.map(item=>{const value=item.toISOString().slice(0,10);return <button key={value} className={date===value?'active':''} onClick={()=>{setDate(value);setStart('')}}><span>{dayFormat.format(item).split(' ')[0]}</span><strong>{item.getDate()}</strong><small>{item.toLocaleDateString('pt-BR',{month:'short'})}</small></button>})}</div>{date&&<><h3 className="slot-heading">Horários em {fullDate.format(new Date(`${date}T12:00:00`))}</h3>{slots.length?<div className="slot-grid">{slots.map(slot=><button key={slot} className={start===slot?'active':''} onClick={()=>setStart(slot)}>{slot}</button>)}</div>:<div className="empty-inline">Não há horários disponíveis nesta data.</div>}</>}
      <h3 className="slot-heading">Modalidade</h3><div className="mode-grid">{service.modes.map(item=><button key={item} className={`mode-option ${mode===item?'active':''}`} onClick={()=>setMode(item)}>{item==='online'?<Monitor/>:item==='office'?<MapPin/>:<Stethoscope/>}<span>{modeLabels[item]}</span></button>)}</div>
      <div className="field" style={{marginTop:18}}><label>Algo que a profissional precisa saber? <span className="muted">(opcional)</span></label><textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Conte brevemente o motivo do atendimento."/></div>
      <button className="btn btn-primary" disabled={!date||!start||!mode} onClick={()=>setStep('confirm')}>Continuar</button></div><BookingSummary profileName={profile.displayName} service={service} date={date} start={start} mode={mode}/></div>}
    {step==='confirm'&&service&&<div className="grid booking-grid"><div className="card"><span className="step-label">Etapa 3 de 3</span><h2>Confirme seu agendamento</h2><div className="confirmation-box"><CheckCircle2/><div><strong>Revise os detalhes ao lado</strong><p>Ao confirmar, o horário ficará reservado e a profissional poderá confirmar o atendimento.</p></div></div>{error&&<div className="form-error">{error}</div>}<button className="btn btn-primary" onClick={submit}>Confirmar agendamento</button></div><BookingSummary profileName={profile.displayName} service={service} date={date} start={start} mode={mode}/></div>}
    {step==='success'&&<div className="card success-card"><div className="success-icon"><CheckCircle2/></div><span className="badge">Horário reservado</span><h2>Seu agendamento foi realizado</h2><p className="muted">A profissional receberá o pedido e poderá confirmar o atendimento. Você acompanha tudo nesta página.</p><button className="btn btn-primary" onClick={()=>{setStep('list');setService(null);setDate('');setStart('');setNote('')}}>Ver meus agendamentos</button></div>}
  </>
}
function BookingSummary({profileName,service,date,start,mode}:{profileName:string;service:ProfessionalService;date:string;start:string;mode:AttendanceMode|null}){return <aside className="card booking-summary"><span className="badge">Resumo</span><h3>{service.name}</h3><div className="summary-line"><Stethoscope size={17}/><span>{profileName}</span></div><div className="summary-line"><CalendarDays size={17}/><span>{date?fullDate.format(new Date(`${date}T12:00:00`)):'Escolha uma data'}</span></div><div className="summary-line"><Clock size={17}/><span>{start?`${start} · ${service.durationMinutes} minutos`:'Escolha um horário'}</span></div><div className="summary-line"><MapPin size={17}/><span>{mode?modeLabels[mode]:'Escolha a modalidade'}</span></div><div className="summary-total"><span>Valor</span><strong>{money.format(service.price)}</strong></div></aside>}
