import { useState } from 'react'
import { CheckCircle2, Copy, CreditCard, QrCode, ReceiptText, ShieldCheck, Wallet } from 'lucide-react'
import { useAuth } from '../../lib/AuthContext'
import { generatePix, getPatientPayments, getPaymentDetails, payPayment, paymentMethodLabels, paymentStatusClass, paymentStatusLabels, type Payment, type PaymentMethod } from '../../lib/payments'
const money = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'})
const date = new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'long',year:'numeric'})

export function PatientPayments(){
 const {user}=useAuth(); const [,refresh]=useState(0); const [selected,setSelected]=useState<Payment|null>(null); const [method,setMethod]=useState<PaymentMethod>('pix'); const [installments,setInstallments]=useState(1); const [success,setSuccess]=useState(''); const [error,setError]=useState('')
 const payments=user?getPatientPayments(user.id).map(getPaymentDetails):[]; const pending=payments.filter(i=>['pending','processing'].includes(i.status)); const paid=payments.filter(i=>i.status==='paid')
 function start(payment:Payment){setSelected(payment);setMethod(payment.method||'pix');setInstallments(1);setSuccess('');setError('')}
 function createPix(){if(!selected)return;const updated=generatePix(selected.id);setSelected(updated);refresh(v=>v+1)}
 function confirm(){if(!selected)return;try{payPayment(selected.id,method,installments);setSuccess('Pagamento confirmado com sucesso.');setSelected(null);refresh(v=>v+1)}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir.') }}
 return <><div className="topbar"><div><h1>Pagamentos</h1><div className="muted">Consultas, cobranças e comprovantes em um só lugar.</div></div></div>
 {success&&<div className="success-banner"><CheckCircle2 size={19}/>{success}</div>}
 <div className="grid grid-3"><div className="card admin-metric"><div className="metric-icon"><Wallet/></div><div><span className="muted">A pagar</span><h2>{money.format(pending.reduce((s,i)=>s+i.amount,0))}</h2></div></div><div className="card admin-metric"><div className="metric-icon"><CheckCircle2/></div><div><span className="muted">Pago</span><h2>{money.format(paid.reduce((s,i)=>s+i.amount,0))}</h2></div></div><div className="card admin-metric"><div className="metric-icon"><ShieldCheck/></div><div><span className="muted">Ambiente protegido</span><h2>Pagamento seguro</h2></div></div></div>
 <div className="card" style={{marginTop:18}}><div className="section-heading"><div><h2>Cobranças</h2><p className="muted">Os pagamentos são vinculados aos seus agendamentos.</p></div></div>{payments.length?<div className="payment-list">{payments.map(item=><div className="payment-row" key={item.id}><div className="payment-icon"><ReceiptText/></div><div><strong>{item.appointment?.serviceName || 'Atendimento profissional'}</strong><span>{item.appointment?`${new Date(`${item.appointment.date}T12:00:00`).toLocaleDateString('pt-BR')} às ${item.appointment.start}`:date.format(new Date(item.createdAt))}</span>{item.method&&<small>{paymentMethodLabels[item.method]}{item.installments&&item.installments>1?` · ${item.installments}x`:''}</small>}</div><strong className="payment-value">{money.format(item.amount)}</strong><span className={`status-pill ${paymentStatusClass[item.status]}`}>{paymentStatusLabels[item.status]}</span>{['pending','processing'].includes(item.status)&&<button className="btn btn-primary btn-small" onClick={()=>start(item)}>Pagar</button>}</div>)}</div>:<div className="empty-state"><ReceiptText/><h3>Nenhuma cobrança</h3><p>Seus pagamentos aparecerão após um agendamento.</p></div>}</div>
 {selected&&<div className="modal-backdrop"><div className="modal-card small"><div className="modal-head"><div><span className="badge">Pagamento simulado</span><h2>{money.format(selected.amount)}</h2><p className="muted">Escolha como deseja pagar.</p></div><button className="icon-btn" onClick={()=>setSelected(null)}>×</button></div><div className="payment-method-grid"><button className={method==='pix'?'active':''} onClick={()=>setMethod('pix')}><QrCode/><strong>Pix</strong><small>Confirmação rápida</small></button><button className={method==='card'?'active':''} onClick={()=>setMethod('card')}><CreditCard/><strong>Cartão</strong><small>Em até 3x sem juros</small></button></div>
 {method==='pix'&&<>{!selected.pixCode?<button className="btn btn-secondary full" onClick={createPix}><QrCode size={18}/> Gerar código Pix</button>:<div className="pix-box"><QrCode size={50}/><strong>Pix copia e cola</strong><code>{selected.pixCode}</code><button className="btn btn-secondary btn-small" onClick={()=>navigator.clipboard?.writeText(selected.pixCode||'')}><Copy size={16}/> Copiar</button></div>}</>}
 {method==='card'&&<div className="form-grid"><div className="field full"><label>Número do cartão</label><input placeholder="0000 0000 0000 0000"/></div><div className="field"><label>Validade</label><input placeholder="MM/AA"/></div><div className="field"><label>CVV</label><input placeholder="000"/></div><div className="field full"><label>Parcelamento</label><select value={installments} onChange={e=>setInstallments(Number(e.target.value))}>{[1,2,3].map(i=><option value={i} key={i}>{i}x de {money.format(selected.amount/i)} sem juros</option>)}</select></div></div>}
 {error&&<div className="form-error">{error}</div>}<button className="btn btn-primary full" disabled={method==='pix'&&!selected.pixCode} onClick={confirm}>Confirmar pagamento</button><p className="simulation-note">Protótipo: nenhum valor real será cobrado.</p></div></div>}
 </>
}
