import { supabase } from './supabase'
export type EcosystemKind='marketplace'|'courses'|'jobs'
export type EcosystemRow={id:string;slug:string;name?:string;title?:string;description:string;category?:string;price_cents?:number;image_url?:string|null;item_condition?:string|null;city?:string|null;state_code?:string|null;contact_url?:string|null;instructor_name?:string;audience?:string;company_name?:string;workplace_type?:string;employment_type?:string;requirements?:string|null;benefits?:string|null;application_url?:string;expires_at?:string|null;status?:string;professional_id?:string|null;organization_id?:string|null;owner_organization_id?:string|null;demo?:boolean}
const demos:Record<EcosystemKind,EcosystemRow[]>={marketplace:[{id:'demo-product-1',slug:'almofada-amamentacao-demonstracao',name:'Almofada de amamentação',description:'Apoio ergonômico para tornar a amamentação mais confortável.',category:'Amamentação',price_cents:14990,demo:true},{id:'demo-product-2',slug:'mochila-maternidade-demonstracao',name:'Mochila maternidade',description:'Organização prática para passeios e rotina com o bebê.',category:'Passeio',price_cents:21990,demo:true},{id:'demo-product-3',slug:'carrinho-infantil-desapego-demonstracao',name:'Carrinho infantil — desapego',description:'Item demonstrativo de desapego em bom estado.',category:'Desapegos',price_cents:65000,item_condition:'used',demo:true}],courses:[{id:'demo-course-1',slug:'preparacao-amamentacao-demonstracao',name:'Preparação para a amamentação',description:'Orientações introdutórias para famílias que desejam se preparar para a amamentação.',category:'Amamentação',audience:'families',price_cents:19700,instructor_name:'Equipe MaterPlace',demo:true},{id:'demo-course-2',slug:'manejo-clinico-lactacao-demonstracao',name:'Atualização em manejo clínico da lactação',description:'Conteúdo demonstrativo de atualização para profissionais.',category:'Amamentação',audience:'professionals',price_cents:39700,instructor_name:'Equipe MaterPlace',demo:true}],jobs:[{id:'demo-job-1',slug:'pediatra-clinica-demonstracao',title:'Pediatra',description:'Oportunidade demonstrativa para atendimento materno-infantil.',company_name:'Clínica Materno Infantil',city:'São Paulo',state_code:'SP',workplace_type:'onsite',employment_type:'pj',requirements:'Registro profissional ativo.',application_url:'mailto:contato@materplace.com.br',demo:true},{id:'demo-job-2',slug:'fonoaudiologo-pediatrico-demonstracao',title:'Fonoaudiólogo Pediátrico',description:'Oportunidade demonstrativa para atendimento presencial.',company_name:'Clínica Materno Infantil',city:'São Paulo',state_code:'SP',workplace_type:'onsite',employment_type:'clt',requirements:'Formação e registro profissional compatíveis.',application_url:'mailto:contato@materplace.com.br',demo:true}]}
const tables:Record<EcosystemKind,string>={marketplace:'marketplace_items',courses:'courses',jobs:'jobs'}
export async function listEcosystem(kind:EcosystemKind){if(!supabase)return demos[kind];const {data,error}=await supabase.from(tables[kind]).select('*').eq('status','published').order('featured',{ascending:false}).order('published_at',{ascending:false}).limit(60);return error||!data?.length?demos[kind]:data as EcosystemRow[]}
export async function getEcosystem(kind:EcosystemKind,slug:string){if(supabase){const {data}=await supabase.from(tables[kind]).select('*').eq('status','published').eq('slug',slug).maybeSingle();if(data)return data as EcosystemRow}return demos[kind].find(item=>item.slug===slug)||null}

export async function listManagedEcosystem(kind:EcosystemKind,own=false){if(!supabase)throw new Error('Banco não configurado.');let query=supabase.from(tables[kind]).select('*').order('created_at',{ascending:false});if(own){const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Sessão expirada.');if(kind==='marketplace')query=query.eq('owner_user_id',user.id);else{const {data:member,error:memberError}=await supabase.from('organization_members').select('organization_id').eq('user_id',user.id).eq('active',true).limit(1).single();if(memberError)throw new Error(memberError.message);query=query.eq('organization_id',member.organization_id)}}const {data,error}=await query;if(error)throw new Error(error.message);return(data??[]) as EcosystemRow[]}
export async function updateEcosystemStatus(kind:EcosystemKind,id:string,status:string,featured?:boolean){if(!supabase)throw new Error('Banco não configurado.');const payload:any={status};if(featured!=null)payload.featured=featured;if(status==='published')payload.published_at=new Date().toISOString();const {error}=await supabase.from(tables[kind]).update(payload).eq('id',id);if(error)throw new Error(error.message)}
export async function uploadEcosystemImage(file:File,folder:string){if(!supabase)throw new Error('Banco não configurado.');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024)throw new Error('Envie JPG, PNG ou WebP de até 10 MB.');const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Sessão expirada.');const path=`${user.id}/${folder}/${crypto.randomUUID()}.${file.name.split('.').pop()?.toLowerCase()||'jpg'}`;const {error}=await supabase.storage.from('marketplace-media').upload(path,file,{contentType:file.type,upsert:false});if(error)throw new Error(error.message);return supabase.storage.from('marketplace-media').getPublicUrl(path).data.publicUrl}
export async function saveEcosystem(kind:EcosystemKind,input:any,id?:string){if(!supabase)throw new Error('Banco não configurado.');const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Sessão expirada.');const {data:member}=await supabase.from('organization_members').select('organization_id').eq('user_id',user.id).eq('active',true).limit(1).maybeSingle();const organizationId=member?.organization_id as string|undefined;if(kind!=='marketplace'&&!organizationId)throw new Error('Sua conta ainda não está vinculada a uma organização.');const cleanSlug=String(input.slug||input.name||input.title||'conteudo').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');const payload={...input,slug:id?input.slug:`${cleanSlug}-${crypto.randomUUID().slice(0,8)}`,status:'pending_review',...(kind==='marketplace'?{owner_user_id:user.id,owner_organization_id:organizationId||null}:{organization_id:organizationId})};const result=id?await supabase.from(tables[kind]).update(payload).eq('id',id):await supabase.from(tables[kind]).insert(payload);if(result.error)throw new Error(result.error.message)}

export async function listProfileEcosystem(kind:'courses'|'jobs',professionalId:string,organizationId?:string){if(!supabase)return[];let query=supabase.from(tables[kind]).select('*').eq('status','published').order('published_at',{ascending:false});query=organizationId?query.or(`professional_id.eq.${professionalId},organization_id.eq.${organizationId}`):query.eq('professional_id',professionalId);const {data,error}=await query;if(error)throw new Error(error.message);return(data??[]) as EcosystemRow[]}
