import { useMemo, useState } from 'react'
import { Ban, CalendarDays, Check, ChevronLeft, ChevronRight, Clock, Filter, Plus, Search, Trash2, UserRound, X } from 'lucide-react'
import { useAuth } from '../../lib/AuthContext'
import { appointmentStatusClass, appointmentStatusLabels, createScheduleBlock, getAppointmentDetails, getProfessionalAppointments, getScheduleBlocks, removeScheduleBlock, updateAppointmentInternalNote, updateAppointmentStatus, type AppointmentStatus } from '../../lib/appointments'
import { modeLabels } from '../../lib/professionalProfile'

const money = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'})
const dateLong = new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long'})
function iso(date:Date){return date.toISOString().slice(0,10)}
function startOfWeek(input:Date){const d=new Date(input);d.setHours(12,0,0,0);const day=d.getDay();d.setDate(d.getDate()-(day===0?6:day-1));return d}
function addDays(date:Date,n:number){const d=new Date(date);d.setDate(d.getDate()+n);return d}

export function ProfessionalAgenda(){
  const { user }=useAuth(); const professionalId=user?.id||''; const [version,setVersion]=useState(0)
  const [week,setWeek]=useState(()=>startOfWeek(new Date())); const [view,setView]=useState<'week'|'list'|'blocks'>('week'); const [query,setQuery]=useState(''); const [status,setStatus]=useState<'all'|AppointmentStatus>('all'); const [showBlock,setShowBlock]=useState(false)
  const appointments=getProfessionalAppointments(professionalId).map(getAppointmentDetails); const blocks=getScheduleBlocks().filter(item=>item.professionalId===professionalId)
  const days=useMemo(()=>Array.from({length:7},(_,i)=>addDays(week,i)),[week])
  const filtered=appointments.filter(item=>(status==='all'||item.status===status)&&item.patientName.toLowerCase().includes(query.toLowerCase()))
  const weekAppointments=appointments.filter(item=>days.some(day=>iso(day)===item.date))
  const activeRevenue=appointments.filter(item=>['scheduled','confirmed','completed'].includes(item.status)).reduce((sum,item)=>sum+item.price,0)
  function changeStatus(id:string,next:AppointmentStatus){updateAppointmentStatus(id,next);setVersion(v=>v+1)}
  return <>
    <div className="topbar"><div><h1>Agenda</h1><div className="muted">Organize atendimentos, bloqueios e confirmações.</div></div><button className="btn btn-primary" onClick={()=>setShowBlock(v=>!v)}><Plus size={18}/> Bloquear horário</button></div>
    <div className="grid grid-4 agenda-metrics"><div className="card"><span className="muted">Nesta semana</span><div className="metric">{weekAppointments.length}</div><small>atendimentos</small></div><div className="card"><span className="muted">Confirmadas</span><div className="metric">{appointments.filter(i=>i.status==='confirmed').length}</div><small>consultas</small></div><div className="card"><span className="muted">Aguardando</span><div className="metric">{appointments.filter(i=>i.status==='scheduled').length}</div><small>confirmações</small></div><div className="card"><span className="muted">Receita prevista</span><div className="metric metric-money">{money.format(activeRevenue)}</div><small>agendamentos ativos</small></div></div>
    {showBlock&&<BlockForm professionalId={professionalId} onDone={()=>{setShowBlock(false);setVersion(v=>v+1)}}/>}
    <div className="agenda-toolbar card"><div className="tabs compact-tabs"><button className={view==='week'?'active':''} onClick={()=>setView('week')}>Semana</button><button className={view==='list'?'active':''} onClick={()=>setView('list')}>Lista</button><button className={view==='blocks'?'active':''} onClick={()=>setView('blocks')}>Bloqueios</button></div>{view==='week'&&<div className="week-nav"><button onClick={()=>setWeek(addDays(week,-7))}><ChevronLeft/></button><strong>{week.toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})} – {addDays(week,6).toLocaleDateString('pt-BR',{day:'2-digit',month:'short',year:'numeric'})}</strong><button onClick={()=>setWeek(addDays(week,7))}><ChevronRight/></button></div>}{view==='list'&&<div className="agenda-filters"><label className="search-field"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar paciente"/></label><label className="select-inline"><Filter size={16}/><select value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="all">Todos os status</option>{Object.entries(appointmentStatusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>}</div>
    {view==='week'&&<WeekView days={days} appointments={weekAppointments} blocks={blocks}/>} 
    {view==='list'&&<div className="card"><div className="appointment-list professional-list">{filtered.length?filtered.map(item=><ProfessionalAppointment key={`${item.id}-${version}`} item={item} onStatus={changeStatus} onNote={()=>setVersion(v=>v+1)}/>):<div className="empty-state"><CalendarDays/><h3>Nenhum atendimento encontrado</h3><p>Ajuste os filtros ou aguarde novos agendamentos.</p></div>}</div></div>}
    {view==='blocks'&&<div className="card"><h2>Horários bloqueados</h2>{blocks.length?<div className="block-list">{blocks.map(block=><div className="block-row" key={block.id}><div className="block-icon"><Ban/></div><div><strong>{dateLong.format(new Date(`${block.date}T12:00:00`))}</strong><span>{block.start} às {block.end} · {block.reason}{block.recurringWeekly?' · repete semanalmente':''}</span></div><button className="icon-btn danger" onClick={()=>{removeScheduleBlock(block.id);setVersion(v=>v+1)}}><Trash2 size={17}/></button></div>)}</div>:<div className="empty-state"><Ban/><h3>Nenhum bloqueio cadastrado</h3><p>Use “Bloquear horário” para férias, compromissos ou pausas.</p></div>}</div>}
  </>
}
function WeekView({days,appointments,blocks}:{days:Date[];appointments:ReturnType<typeof getAppointmentDetails>[];blocks:ReturnType<typeof getScheduleBlocks>}){return <div className="week-calendar">{days.map(day=>{const date=iso(day);const items=appointments.filter(item=>item.date===date);const dayBlocks=blocks.filter(item=>item.date===date);return <div className="week-day" key={date}><div className={`week-day-head ${date===iso(new Date())?'today':''}`}><span>{day.toLocaleDateString('pt-BR',{weekday:'short'})}</span><strong>{day.getDate()}</strong></div><div className="week-day-body">{items.map(item=><div className={`calendar-event ${appointmentStatusClass[item.status]}`} key={item.id}><strong>{item.start}</strong><span>{item.patientName}</span><small>{item.serviceName}</small></div>)}{dayBlocks.map(block=><div className="calendar-block" key={block.id}><strong>{block.start}</strong><span>Bloqueado</span><small>{block.reason}</small></div>)}{!items.length&&!dayBlocks.length&&<span className="day-empty">Livre</span>}</div></div>})}</div>}
function ProfessionalAppointment({item,onStatus,onNote}:{item:ReturnType<typeof getAppointmentDetails>;onStatus:(id:string,status:AppointmentStatus)=>void;onNote:()=>void}){const [open,setOpen]=useState(false);const [note,setNote]=useState(item.internalNote||'');return <div className="professional-appointment"><div className="date-tile"><strong>{item.date.slice(8,10)}</strong><span>{new Date(`${item.date}T12:00:00`).toLocaleDateString('pt-BR',{month:'short'})}</span></div><div className="appointment-main"><div className="row"><UserRound size={17}/><strong>{item.patientName}</strong></div><span>{item.start}–{item.end} · {item.serviceName}</span><small>{modeLabels[item.mode]} · {money.format(item.price)}</small></div><span className={`status-pill ${appointmentStatusClass[item.status]}`}>{appointmentStatusLabels[item.status]}</span><div className="appointment-actions"><button className="btn btn-secondary btn-small" onClick={()=>setOpen(v=>!v)}>Detalhes</button>{item.status==='scheduled'&&<button className="icon-btn success" title="Confirmar" onClick={()=>onStatus(item.id,'confirmed')}><Check size={17}/></button>}{!['completed','cancelled','no_show'].includes(item.status)&&<button className="icon-btn danger" title="Cancelar" onClick={()=>onStatus(item.id,'cancelled')}><X size={17}/></button>}</div>{open&&<div className="appointment-detail"><p><strong>Observação da paciente:</strong> {item.patientNote||'Nenhuma observação.'}</p><div className="field"><label>Anotação interna</label><textarea rows={2} value={note} onChange={e=>setNote(e.target.value)} placeholder="Visível apenas para você"/></div><div className="action-buttons"><button className="btn btn-secondary btn-small" onClick={()=>{updateAppointmentInternalNote(item.id,note);onNote()}}>Salvar anotação</button>{item.status==='confirmed'&&<button className="btn btn-primary btn-small" onClick={()=>onStatus(item.id,'completed')}>Concluir atendimento</button>}{item.status==='confirmed'&&<button className="btn btn-secondary btn-small" onClick={()=>onStatus(item.id,'no_show')}>Marcar ausência</button>}</div></div>}</div>}
function BlockForm({professionalId,onDone}:{professionalId:string;onDone:()=>void}){const [date,setDate]=useState('');const [start,setStart]=useState('09:00');const [end,setEnd]=useState('10:00');const [reason,setReason]=useState('Compromisso pessoal');const [recurringWeekly,setRecurring]=useState(false);const [error,setError]=useState('');function submit(e:React.FormEvent){e.preventDefault();if(!date||!start||!end||!reason){setError('Preencha todos os campos.');return}if(start>=end){setError('O horário final precisa ser posterior ao inicial.');return}createScheduleBlock({professionalId,date,start,end,reason,recurringWeekly});onDone()}return <form className="card block-form" onSubmit={submit}><div className="section-heading"><div><span className="badge">Novo bloqueio</span><h2>Reserve um período na sua agenda</h2></div></div><div className="form-grid"><div className="field"><label>Data</label><input type="date" value={date} onChange={e=>setDate(e.target.value)} min={new Date().toISOString().slice(0,10)}/></div><div className="field"><label>Motivo</label><input value={reason} onChange={e=>setReason(e.target.value)}/></div><div className="field"><label>Início</label><input type="time" value={start} onChange={e=>setStart(e.target.value)}/></div><div className="field"><label>Fim</label><input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></div></div><label className="check-row"><input type="checkbox" checked={recurringWeekly} onChange={e=>setRecurring(e.target.checked)}/> Repetir este bloqueio toda semana</label>{error&&<div className="form-error">{error}</div>}<div className="action-buttons"><button className="btn btn-primary" type="submit">Salvar bloqueio</button><button className="btn btn-secondary" type="button" onClick={onDone}>Cancelar</button></div></form>}
