import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, Plus, RefreshCw, X } from 'lucide-react'
import { createAppointment, listAppointments, listOrganizationProfessionals, listPatients, markAppointmentPaid, rescheduleAppointment, updateAppointment, type RealAppointment } from '../../lib/operations'

type AgendaView='day'|'week'|'month'|'list'
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'})
const labels:Record<RealAppointment['status'],string>={scheduled:'Agendada',confirmed:'Confirmada',waiting:'Aguardando',in_service:'Em atendimento',completed:'Concluída',cancelled:'Cancelada',no_show:'Não compareceu',rescheduled:'Reagendada'}
const dayKey=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`
const startOfWeek=(date:Date)=>{const next=new Date(date);next.setHours(0,0,0,0);next.setDate(next.getDate()-((next.getDay()+6)%7));return next}

export function ProfessionalAgenda(){
  const [items,setItems]=useState<RealAppointment[]>([]),[patients,setPatients]=useState<any[]>([]),[professionals,setProfessionals]=useState<any[]>([])
  const [view,setView]=useState<AgendaView>('week'),[cursor,setCursor]=useState(new Date()),[show,setShow]=useState(false),[editing,setEditing]=useState<RealAppointment|null>(null)
  const [error,setError]=useState(''),[notice,setNotice]=useState('')
  async function load(){setError('');try{const [a,p,pr]=await Promise.all([listAppointments(),listPatients('',0,200),listOrganizationProfessionals()]);setItems(a);setPatients(p);setProfessionals(pr)}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar agenda.')}}
  useEffect(()=>{void load()},[])
  const range=useMemo(()=>{const start=new Date(cursor);start.setHours(0,0,0,0);if(view==='week'){const monday=startOfWeek(start);return{start:monday,end:new Date(monday.getTime()+7*86400000)}}if(view==='month')return{start:new Date(start.getFullYear(),start.getMonth(),1),end:new Date(start.getFullYear(),start.getMonth()+1,1)};if(view==='day')return{start,end:new Date(start.getTime()+86400000)};return{start:new Date(0),end:new Date(8640000000000000)}},[cursor,view])
  const visible=items.filter(item=>{const value=new Date(item.starts_at);return value>=range.start&&value<range.end})
  const days=useMemo(()=>{if(view==='week')return Array.from({length:7},(_,i)=>new Date(range.start.getTime()+i*86400000));if(view==='month'){const first=startOfWeek(range.start);return Array.from({length:42},(_,i)=>new Date(first.getTime()+i*86400000))}return[cursor]},[view,range.start,cursor])
  function navigate(direction:number){setCursor(current=>{const next=new Date(current);if(view==='month')next.setMonth(next.getMonth()+direction);else next.setDate(next.getDate()+direction*(view==='day'?1:7));return next})}
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const starts=new Date(String(f.get('starts'))),ends=new Date(starts.getTime()+Number(f.get('duration'))*60000);try{if(editing){await rescheduleAppointment(editing.id,starts.toISOString(),ends.toISOString(),String(f.get('reason')||''));setNotice('Consulta reagendada e histórico preservado.')}else{await createAppointment({patientId:String(f.get('patient')),professionalId:String(f.get('professional')),startsAt:starts.toISOString(),endsAt:ends.toISOString(),price:Number(String(f.get('price')).replace(',','.')),isOnline:f.get('online')==='on',isReturn:f.get('return')==='on',isPaidReturn:f.get('paidReturn')==='on',notes:String(f.get('notes')||'')});setNotice('Agendamento salvo no banco.')}setShow(false);setEditing(null);await load()}catch(reason){setError(reason instanceof Error?reason.message:'Falha ao salvar agendamento.')}}
  return <><div className="topbar"><div><h1>Agenda</h1><div className="muted">Visão integrada por profissional e paciente.</div></div><div className="row"><button className="icon-btn" title="Atualizar" onClick={()=>void load()}><RefreshCw/></button><button className="btn btn-primary" onClick={()=>{setEditing(null);setShow(true)}}><Plus/> Novo agendamento</button></div></div>
    {error&&<div className="alert alert-error">{error}</div>}{notice&&<div className="success-banner">{notice}</div>}
    <div className="card agenda-toolbar"><strong className="agenda-period-title">{view==='month'?cursor.toLocaleDateString('pt-BR',{month:'long',year:'numeric'}).toUpperCase():`${range.start.toLocaleDateString('pt-BR')} — ${new Date(range.end.getTime()-1).toLocaleDateString('pt-BR')}`}</strong><div className="finance-tabs compact-tabs">{([['day','Dia'],['week','Semana'],['month','Mês'],['list','Lista']] as [AgendaView,string][]).map(([id,label])=><button className={view===id?'active':''} onClick={()=>setView(id)} key={id}>{label}</button>)}</div><div className="row"><button className="icon-btn" aria-label="Período anterior" onClick={()=>navigate(-1)}><ChevronLeft/></button><button className="btn btn-secondary" onClick={()=>setCursor(new Date())}>Hoje</button><button className="icon-btn" aria-label="Próximo período" onClick={()=>navigate(1)}><ChevronRight/></button></div></div>
    {view!=='list'?<section className={`agenda-grid agenda-${view}`}>{days.map(day=>{const rows=items.filter(item=>dayKey(new Date(item.starts_at))===dayKey(day));return <article className={`card agenda-day ${dayKey(day)===dayKey(new Date())?'is-today':''}`} key={day.toISOString()}><header><strong>{day.toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit'})}</strong><span>{rows.length}</span></header>{rows.map(item=><Appointment item={item} edit={item=>{setEditing(item);setShow(true)}} load={load} notice={setNotice} key={item.id}/>)}{!rows.length&&<small className="muted">Livre</small>}</article>})}</section>:<section className="card"><div className="appointment-list">{visible.map(item=><Appointment item={item} edit={item=>{setEditing(item);setShow(true)}} load={load} notice={setNotice} key={item.id}/>)}{!visible.length&&<div className="empty-state"><p className="muted">Nenhum agendamento registrado.</p></div>}</div></section>}
    {show&&<AppointmentForm editing={editing} patients={patients} professionals={professionals} submit={submit} close={()=>{setShow(false);setEditing(null)}}/>}
  </>
}

function Appointment({item,edit,load,notice}:{item:RealAppointment;edit:(item:RealAppointment)=>void;load:()=>Promise<void>;notice:(text:string)=>void}){
  return <div className="professional-appointment compact-appointment"><div className="appointment-main"><strong>{item.patient_profiles?.full_name||'Paciente'}</strong><span><Clock3 size={14}/>{new Date(item.starts_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})} · {item.professional_profiles?.full_name||'Profissional'}</span><small>{item.is_online?'Online':'Presencial'} · {money.format(item.price_cents/100)}</small></div><span className="status-pill">{labels[item.status]}</span><div className="appointment-actions"><button className="btn btn-secondary btn-small" onClick={()=>edit(item)}>Reagendar</button>{item.status==='scheduled'&&<button className="icon-btn success" title="Confirmar" onClick={async()=>{await updateAppointment(item.id,{status:'confirmed'});await load()}}><Check/></button>}{!['completed','cancelled'].includes(item.status)&&<button className="icon-btn danger" title="Cancelar" onClick={async()=>{await updateAppointment(item.id,{status:'cancelled'});await load()}}><X/></button>}{!['completed','cancelled'].includes(item.status)&&<button className="btn btn-primary btn-small" onClick={async()=>{const method=window.prompt('Forma de pagamento (Pix, dinheiro, cartão...)','Pix');if(method){await markAppointmentPaid(item,method);notice('Atendimento e recebimento registrados.');await load()}}}>Marcar pago</button>}</div></div>
}

function AppointmentForm({editing,patients,professionals,submit,close}:{editing:RealAppointment|null;patients:any[];professionals:any[];submit:(e:React.FormEvent<HTMLFormElement>)=>Promise<void>;close:()=>void}){
  const local=editing?new Date(new Date(editing.starts_at).getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):''
  return <div className="modal-backdrop"><form className="modal-card customer-form" onSubmit={submit}><div className="modal-head"><div><h2>{editing?'Reagendar consulta':'Novo agendamento'}</h2><p className="muted">A alteração será persistida e ficará registrada.</p></div><button type="button" className="icon-btn" onClick={close}>×</button></div><div className="form-grid"><label className="field"><span>Paciente</span><select name="patient" required disabled={Boolean(editing)} defaultValue={editing?.patient_id||''}><option value="">Selecione</option>{patients.map(p=><option value={p.id} key={p.id}>{p.full_name}</option>)}</select></label><label className="field"><span>Profissional</span><select name="professional" required disabled={Boolean(editing)} defaultValue={editing?.professional_id||''}><option value="">Selecione</option>{professionals.map(p=><option value={p.id} key={p.id}>{p.full_name}</option>)}</select></label><label className="field"><span>Data e hora</span><input name="starts" type="datetime-local" defaultValue={local} required/></label><label className="field"><span>Duração (minutos)</span><input name="duration" type="number" min="10" defaultValue={editing?Math.round((new Date(editing.ends_at).getTime()-new Date(editing.starts_at).getTime())/60000):60} required/></label>{editing?<label className="field field-span-2"><span>Motivo do reagendamento</span><textarea name="reason" rows={3}/></label>:<><label className="field"><span>Valor (R$)</span><input name="price" inputMode="decimal" defaultValue="0" required/></label><label className="check-row"><input name="online" type="checkbox"/><span>Consulta online</span></label><label className="check-row"><input name="return" type="checkbox"/><span>É retorno</span></label><label className="check-row"><input name="paidReturn" type="checkbox"/><span>Retorno pago</span></label><label className="field field-span-2"><span>Observações</span><textarea name="notes"/></label></>}</div><div className="modal-actions"><button type="button" className="btn btn-secondary" onClick={close}>Cancelar</button><button className="btn btn-primary">{editing?'Confirmar reagendamento':'Salvar'}</button></div></form></div>
}
