import { useState } from 'react'
import { ArrowDownToLine, BadgeDollarSign, CircleDollarSign, Clock3, Landmark, ReceiptText, TrendingUp } from 'lucide-react'
import { useAuth } from '../../lib/AuthContext'
import { getPaymentDetails, getProfessionalPayments, getProfessionalWithdrawals, getWalletSummary, paymentMethodLabels, paymentStatusClass, paymentStatusLabels, requestWithdrawal, withdrawalStatusLabels } from '../../lib/payments'
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'})
export function ProfessionalFinance(){const {user}=useAuth();const [,refresh]=useState(0);const [open,setOpen]=useState(false);const [amount,setAmount]=useState('');const [bank,setBank]=useState('Pix •••• 1234');const [error,setError]=useState('');if(!user)return null;const payments=getProfessionalPayments(user.id).map(getPaymentDetails);const summary=getWalletSummary(user.id);const withdrawals=getProfessionalWithdrawals(user.id)
function withdraw(){try{requestWithdrawal(user.id,Number(amount.replace(',','.')),bank);setOpen(false);setAmount('');setError('');refresh(v=>v+1)}catch(e){setError(e instanceof Error?e.message:'Não foi possível solicitar.') }}
return <><div className="topbar"><div><h1>Financeiro</h1><div className="muted">Recebimentos, taxas, comissões e carteira.</div></div><button className="btn btn-primary" onClick={()=>setOpen(true)} disabled={summary.available<=0}><ArrowDownToLine size={18}/> Solicitar saque</button></div><div className="wallet-hero"><div><span>Saldo disponível</span><h1>{money.format(summary.available)}</h1><small>Valores de atendimentos já pagos, após taxas e comissões.</small></div><div className="wallet-hero-icon"><Landmark/></div></div><div className="grid grid-4" style={{marginTop:18}}><Metric icon={CircleDollarSign} label="Recebido" value={money.format(summary.totalReceived)}/><Metric icon={TrendingUp} label="Líquido" value={money.format(summary.net)}/><Metric icon={BadgeDollarSign} label="Comissões" value={money.format(summary.commissions)}/><Metric icon={Clock3} label="A receber" value={money.format(summary.pending)}/></div><div className="finance-columns"><div className="card"><h2>Movimentações</h2><div className="payment-list">{payments.map(item=><div className="payment-row compact" key={item.id}><div className="payment-icon"><ReceiptText/></div><div><strong>{item.patientName}</strong><span>{item.appointment?.serviceName||'Atendimento'}</span><small>{item.method?paymentMethodLabels[item.method]:'Forma de pagamento não definida'}</small></div><strong className="payment-value">{money.format(item.professionalNet)}</strong><span className={`status-pill ${paymentStatusClass[item.status]}`}>{paymentStatusLabels[item.status]}</span></div>)}</div></div><div className="card"><h2>Saques</h2>{withdrawals.length?<div className="withdrawal-list">{withdrawals.map(item=><div className="withdrawal-row" key={item.id}><Landmark/><div><strong>{money.format(item.amount)}</strong><span>{item.bankLabel}</span></div><span className="badge">{withdrawalStatusLabels[item.status]}</span></div>)}</div>:<div className="empty-inline">Nenhum saque solicitado.</div>}<div className="fee-summary"><div><span>Taxa da plataforma</span><strong>{money.format(summary.fees)}</strong></div><div><span>Comissões de indicação</span><strong>{money.format(summary.commissions)}</strong></div></div></div></div>
{open&&<div className="modal-backdrop"><div className="modal-card small"><div className="modal-head"><div><h2>Solicitar saque</h2><p className="muted">Disponível: {money.format(summary.available)}</p></div><button className="icon-btn" onClick={()=>setOpen(false)}>×</button></div><div className="field"><label>Valor</label><input value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0,00"/></div><div className="field"><label>Conta de destino</label><select value={bank} onChange={e=>setBank(e.target.value)}><option>Pix •••• 1234</option><option>Banco Rede • Ag. 0001 • C/C •••• 8821</option></select></div>{error&&<div className="form-error">{error}</div>}<button className="btn btn-primary full" onClick={withdraw}>Confirmar solicitação</button></div></div>}</>}
function Metric({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <div className="card admin-metric"><div className="metric-icon"><Icon/></div><div><span className="muted">{label}</span><h2>{value}</h2></div></div>}
