import { useMemo, useState } from 'react'
import { Search, Send, BadgeDollarSign, Users } from 'lucide-react'
import { useAuth } from '../../lib/AuthContext'
import { getUsers } from '../../lib/auth'
import { createReferral, getReferralView } from '../../lib/referrals'

export function ProfessionalNetwork(){
 const {user}=useAuth(); const [refresh,setRefresh]=useState(0); const [query,setQuery]=useState(''); const [selected,setSelected]=useState('professional-1'); const [patient,setPatient]=useState({name:'',email:'',service:'',amount:'390'}); const [message,setMessage]=useState('')
 const professionals=useMemo(()=>getUsers().filter(u=>u.role==='professional'&&u.status==='active'&&u.id!==user?.id&&u.plan!=='free'&&(`${u.name} ${u.specialty}`).toLowerCase().includes(query.toLowerCase())),[query,user?.id,refresh])
 const referrals=user?getReferralView(user.id):[]; const earned=referrals.reduce((s,r)=>s+r.commission,0)
 function submit(e:React.FormEvent){e.preventDefault();if(!user)return;createReferral({referrerId:user.id,receiverId:selected,patientName:patient.name,patientEmail:patient.email,service:patient.service,amount:Number(patient.amount)});setPatient({name:'',email:'',service:'',amount:'390'});setMessage('Indicação registrada. A comissão será liberada quando o pagamento for confirmado.');setRefresh(v=>v+1)}
 return <div><div className="page-heading"><div><span className="badge">Rede profissional</span><h1>Indicações</h1><p className="muted">Indique profissionais do Plano Anual e receba 20% quando a paciente fechar.</p></div></div>
 <div className="grid grid-3"><div className="card"><BadgeDollarSign/><div className="metric">{earned.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</div><span className="muted">Comissões liberadas</span></div><div className="card"><Send/><div className="metric">{referrals.filter(r=>r.referrerId===user?.id).length}</div><span className="muted">Indicações enviadas</span></div><div className="card"><Users/><div className="metric">{professionals.length}</div><span className="muted">Profissionais aptas a receber</span></div></div>
 <div className="grid grid-2" style={{marginTop:20}}><form className="card" onSubmit={submit}><h2>Nova indicação</h2>{message&&<div className="alert alert-success">{message}</div>}<label className="field"><span>Profissional indicada</span><select value={selected} onChange={e=>setSelected(e.target.value)}>{professionals.map(p=><option value={p.id} key={p.id}>{p.name} · {p.specialty}</option>)}</select></label><label className="field"><span>Nome da paciente</span><input required value={patient.name} onChange={e=>setPatient({...patient,name:e.target.value})}/></label><label className="field"><span>E-mail da paciente</span><input type="email" required value={patient.email} onChange={e=>setPatient({...patient,email:e.target.value})}/></label><label className="field"><span>Atendimento indicado</span><input required value={patient.service} onChange={e=>setPatient({...patient,service:e.target.value})}/></label><label className="field"><span>Valor estimado</span><input type="number" min="1" required value={patient.amount} onChange={e=>setPatient({...patient,amount:e.target.value})}/></label><button className="btn btn-primary">Registrar indicação</button></form>
 <div className="card"><h2>Encontrar profissional</h2><div className="search-box"><Search size={18}/><input placeholder="Nome ou especialidade" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="stack" style={{marginTop:16}}>{professionals.map(p=><div className="list-item" key={p.id}><div><strong>{p.name}</strong><small>{p.specialty} · {p.city}</small></div><span className="badge">Plano Anual</span></div>)}</div></div></div>
 <div className="card" style={{marginTop:20}}><h2>Histórico de indicações</h2><div className="table-wrap"><table><thead><tr><th>Paciente</th><th>Profissional</th><th>Valor</th><th>Status</th><th>Comissão</th></tr></thead><tbody>{referrals.map(r=><tr key={r.id}><td>{r.patientName}<small>{r.service}</small></td><td>{r.receiver?.name}</td><td>{r.amount.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</td><td><span className="badge">{r.status}</span></td><td>{r.commission.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</td></tr>)}</tbody></table></div></div></div>
}
