import { useEffect, useMemo, useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { MapPin, Search } from 'lucide-react'
import { Logo } from '../../components/Logo'
import { Seo } from '../../components/Seo'
import { listDirectoryFallback, searchProfessionalDirectory, type DirectoryProfessional } from '../../lib/operations'
import { LegalFooter } from './Legal'

const titleCase=(value:string)=>value.replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase())
const profileHref=(p:DirectoryProfessional)=>`/profissional/${p.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}-${p.id}`

export function DirectoryLanding(){
  const {specialty='',uf='',city=''}=useParams(); const [params,setParams]=useSearchParams(); const page=Math.max(1,Number(params.get('pagina')||1));
  const [rows,setRows]=useState<DirectoryProfessional[]>([]); const [fallback,setFallback]=useState<DirectoryProfessional[]>([]); const [error,setError]=useState(''); const pageSize=20
  const specialtyName=titleCase(specialty); const cityName=titleCase(city); const state=uf.toUpperCase()
  useEffect(()=>{setError('');Promise.all([searchProfessionalDirectory(specialty,uf,city,page,pageSize),listDirectoryFallback(specialty,uf,city)]).then(([a,b])=>{setRows(a);setFallback(b)}).catch(e=>setError(e instanceof Error?e.message:'Não foi possível carregar o diretório.'))},[specialty,uf,city,page])
  const total=Number(rows[0]?.total_count||0); const pages=Math.max(1,Math.ceil(total/pageSize));
  const schema=useMemo(()=>[{'@context':'https://schema.org','@type':'ItemList',name:`${specialtyName} em ${cityName}`,numberOfItems:total,itemListElement:rows.map((p,i)=>({'@type':'ListItem',position:(page-1)*pageSize+i+1,url:`https://materplace.com.br${profileHref(p)}`,name:p.name}))},{'@context':'https://schema.org','@type':'FAQPage',mainEntity:[{'@type':'Question',name:`Como encontrar ${specialtyName} em ${cityName}?`,acceptedAnswer:{'@type':'Answer',text:'Consulte os perfis revisados pela MaterPlace e compare localização e informações profissionais.'}},{'@type':'Question',name:`Quais profissionais estão cadastrados em ${cityName}?`,acceptedAnswer:{'@type':'Answer',text:`A lista é atualizada conforme novos perfis de ${specialtyName} passam pela revisão técnica da plataforma.`}}]}],[specialtyName,cityName,total,rows,page])
  return <div className="marketplace-page"><Seo title={`${specialtyName} em ${cityName} - ${state} | Diretório MaterPlace`} description={`Procurando por ${specialtyName} em ${cityName} - ${state}? Confira clínicas e especialistas cadastrados no portal MaterPlace.`} schema={schema}/><header className="portal-topbar"><Link to="/"><Logo/></Link><Link className="btn btn-secondary" to="/cadastro-profissional">Cadastre-se</Link></header><main className="directory-shell"><header className="directory-hero"><span className="badge">Diretório MaterPlace</span><h1>{specialtyName} em {cityName} - {state}</h1><p>Encontre profissionais de {specialtyName} atuantes na região de {cityName} - {state}. Confira a lista completa de especialistas revisados no portal.</p></header>{error&&<div className="alert alert-error">{error}</div>}<section className="directory-grid">{rows.map(p=><article className="directory-card" key={p.id}><div className="directory-avatar">{p.name.split(' ').slice(0,2).map(x=>x[0]).join('')}</div><div><h2>{p.name}</h2><strong>{p.primary_specialty}</strong><p><MapPin/> {[p.neighborhood,p.city,p.state_code].filter(Boolean).join(' · ')}</p><small>Dados de contato protegidos</small></div><Link className="btn btn-secondary" to={profileHref(p)}>Ver perfil</Link></article>)}</section>{!rows.length&&!error&&<section className="card empty-state"><Search/><h2>Ainda estamos expandindo a rede de {specialtyName} em {cityName} - {state}.</h2><p>Os cadastros encontrados passam por revisão humana antes de aparecerem publicamente.</p><Link className="btn btn-primary" to="/cadastro-profissional">É profissional ou clínica? Cadastre-se</Link></section>}{!rows.length&&fallback.length>0&&<section><h2>Profissionais em outras cidades de {state}</h2><div className="directory-grid">{fallback.map(p=><article className="directory-card" key={p.id}><div><h3>{p.name}</h3><p>{p.primary_specialty} · {p.city}/{p.state_code}</p></div><Link to={profileHref(p)}>Ver perfil</Link></article>)}</div></section>}{pages>1&&<nav className="directory-pagination" aria-label="Paginação">{Array.from({length:pages},(_,i)=>i+1).map(n=><button className={n===page?'active':''} key={n} onClick={()=>setParams({pagina:String(n)})}>{n}</button>)}</nav>}<section className="directory-faq"><h2>Perguntas frequentes</h2><h3>Como encontrar {specialtyName} em {cityName}?</h3><p>Use a lista acima e abra o perfil para verificar as informações públicas revisadas.</p><h3>Como um profissional entra no diretório?</h3><p>O profissional pode criar ou reivindicar o perfil e completar a validação da MaterPlace.</p></section></main><LegalFooter/></div>
}

