import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { MapPin, ShieldCheck } from 'lucide-react'
import { Logo } from '../../components/Logo'
import { Seo } from '../../components/Seo'
import { getDirectoryProfessional, type DirectoryProfessional } from '../../lib/operations'
import { LegalFooter } from './Legal'

export function DirectoryProfile(){const {slug=''}=useParams();const id=slug.match(/([0-9a-f]{8}-[0-9a-f-]{27})$/i)?.[1]||'';const [row,setRow]=useState<DirectoryProfessional|null>();useEffect(()=>{if(id)getDirectoryProfessional(id).then(setRow).catch(()=>setRow(null));else setRow(null)},[id]);if(row===undefined)return <div className="auth-page">Carregando perfil...</div>;if(!row)return <div className="auth-page"><div className="auth-card"><Logo/><h1>Perfil não encontrado</h1><Link to="/">Voltar ao início</Link></div></div>;const premium=row.is_claimed&&row.plan_type==='premium';return <div className="clinic-profile-page"><Seo title={`${row.name} — ${row.primary_specialty} em ${row.city}`} description={`${row.name}, ${row.primary_specialty} em ${row.neighborhood?`${row.neighborhood}, `:''}${row.city}/${row.state_code}.`} schema={{'@context':'https://schema.org','@type':'MedicalBusiness',name:row.name,medicalSpecialty:row.primary_specialty,address:{'@type':'PostalAddress',addressLocality:row.city,addressRegion:row.state_code,addressNeighborhood:row.neighborhood}}}/><header className="portal-topbar compact"><Link to="/"><Logo/></Link></header><main className="clinic-profile-shell"><section className="card directory-profile-card"><ShieldCheck/><h1>{row.name}</h1><h2>{row.primary_specialty}</h2><p><MapPin/> {[row.neighborhood,row.city,row.state_code].filter(Boolean).join(' · ')}</p>{premium?<p>Perfil Premium reivindicado. As informações completas serão exibidas após a vinculação à conta profissional.</p>:<div className="claim-profile"><h2>Este perfil ainda não foi reivindicado</h2><p>Por privacidade, telefone, WhatsApp, e-mail e endereço completo não são exibidos.</p><Link className="btn btn-primary" to="/cadastro-profissional">É responsável por este perfil? Reivindique agora</Link></div>}</section></main><LegalFooter/></div>}
