import { useEffect,useMemo,useState } from 'react'
import { ArrowLeft,BookOpen,BriefcaseBusiness,MapPin,Search,ShoppingBag } from 'lucide-react'
import { Link,useParams } from 'react-router-dom'
import { Logo } from '../../components/Logo'
import { Seo } from '../../components/Seo'
import { getEcosystem,listEcosystem,type EcosystemKind,type EcosystemRow } from '../../lib/ecosystem'
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'})
const config={marketplace:{title:'Marketplace MaterPlace',description:'Produtos selecionados para maternidade, infância e família.',singular:'Produto',icon:ShoppingBag},courses:{title:'Universidade MaterPlace',description:'Cursos confiáveis para famílias e profissionais.',singular:'Curso',icon:BookOpen},jobs:{title:'Vagas MaterPlace',description:'Oportunidades no ecossistema materno-infantil e da saúde.',singular:'Vaga',icon:BriefcaseBusiness}}
const label=(row:EcosystemRow)=>row.name||row.title||'MaterPlace'
const pathFor=(kind:EcosystemKind,slug:string)=>kind==='marketplace'?`/marketplace/produto/${slug}`:kind==='courses'?`/universidade/curso/${slug}`:`/vagas/${slug}`
export function EcosystemListing({kind}:{kind:EcosystemKind}){const [rows,setRows]=useState<EcosystemRow[]>([]),[query,setQuery]=useState(''),[filter,setFilter]=useState('');useEffect(()=>{void listEcosystem(kind).then(setRows)},[kind]);const categories=[...new Set(rows.map(row=>kind==='jobs'?row.workplace_type:kind==='courses'?row.audience:row.category).filter(Boolean))] as string[];const visible=useMemo(()=>rows.filter(row=>(!filter||(kind==='jobs'?row.workplace_type:kind==='courses'?row.audience:row.category)===filter)&&`${label(row)} ${row.description} ${row.city||''}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))),[rows,query,filter,kind]);const c=config[kind],Icon=c.icon;return <div className="ecosystem-page"><Seo title={c.title} description={c.description}/><header className="ecosystem-nav"><Link to="/"><Logo/></Link><nav><Link to="/marketplace">Marketplace</Link><Link to="/universidade">Universidade</Link><Link to="/vagas">Vagas</Link></nav></header><main><section className="ecosystem-hero"><Icon/><span className="badge">Ecossistema MaterPlace</span><h1>{c.title}</h1><p>{c.description}</p></section><section className="ecosystem-tools"><label className="search-field"><Search/><input aria-label={`Buscar em ${c.title}`} value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Buscar ${c.singular.toLocaleLowerCase('pt-BR')}...`}/></label><select aria-label="Filtrar" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todos</option>{categories.map(item=><option key={item}>{item}</option>)}</select>{kind==='marketplace'&&<Link className="btn btn-primary" to="/cadastro-profissional">Venda seu produto</Link>}</section><section className="ecosystem-grid">{visible.map(row=><article className="ecosystem-card" key={row.id}>{row.image_url?<img src={row.image_url} alt=""/>:<div className="ecosystem-art"><Icon/></div>}<div>{row.demo&&<small>Conteúdo demonstrativo</small>}<h2><Link to={pathFor(kind,row.slug)}>{label(row)}</Link></h2><p>{row.description}</p>{row.city&&<span><MapPin/> {row.city}/{row.state_code}</span>}{typeof row.price_cents==='number'&&<strong>{money.format(row.price_cents/100)}</strong>}<Link className="story-link" to={pathFor(kind,row.slug)}>Ver detalhes</Link></div></article>)}{!visible.length&&<div className="empty-state"><h2>Nenhum resultado encontrado</h2><p>Tente alterar a busca ou o filtro.</p></div>}</section></main></div>}
export function EcosystemDetail({kind}:{kind:EcosystemKind}){const {slug=''}=useParams(),[row,setRow]=useState<EcosystemRow|null|undefined>();useEffect(()=>{void getEcosystem(kind,slug).then(setRow)},[kind,slug]);if(row===undefined)return <main className="route-loading">Carregando...</main>;if(!row)return <main className="empty-state"><Seo title="Conteúdo não encontrado" description="Este conteúdo não está disponível." index={false}/><h1>Conteúdo não encontrado</h1><Link to={kind==='courses'?'/universidade':`/${kind}`}><ArrowLeft/> Voltar</Link></main>;const c=config[kind],title=label(row),contact=row.contact_url||row.application_url;return <div className="ecosystem-page"><Seo title={title} description={row.description} image={row.image_url}/><header className="ecosystem-nav"><Link to="/"><Logo/></Link></header><main className="ecosystem-detail"><Link className="story-link" to={kind==='courses'?'/universidade':`/${kind}`}><ArrowLeft/> Voltar para {c.title}</Link><article>{row.image_url&&<img src={row.image_url} alt={title}/>}<span className="badge">{row.category||row.company_name||c.singular}</span>{row.demo&&<small>Conteúdo demonstrativo</small>}<h1>{title}</h1><p>{row.description}</p>{row.requirements&&<><h2>Requisitos</h2><p>{row.requirements}</p></>}{row.benefits&&<><h2>Benefícios</h2><p>{row.benefits}</p></>}{row.city&&<p><MapPin/> {row.city}/{row.state_code}</p>}{typeof row.price_cents==='number'&&<strong className="ecosystem-price">{money.format(row.price_cents/100)}</strong>}{contact?<a className="btn btn-primary" href={contact} rel="nofollow noopener">{kind==='jobs'?'Candidatar-se':'Tenho interesse'}</a>:<p className="muted">O responsável ainda não informou um canal de contato.</p>}</article></main></div>}
