import { Link } from 'react-router-dom'
import { CalendarDays, Check, HeartHandshake, MessageCircle, Network, ShieldCheck, Wallet } from 'lucide-react'
import { Logo } from '../../components/Logo'

const free=['Cadastro e perfil profissional','Busca na rede','Links de indicação','20% de comissão quando a paciente fechar']
const annual=['Indicar e receber indicações','Agenda e portal da paciente','Chat e plano de cuidados','Prontuário compartilhado autorizado','Pagamentos, carteira e relatórios']
export function Landing(){return <>
<header style={{maxWidth:1180,margin:'auto',padding:'20px 24px',display:'flex',justifyContent:'space-between',alignItems:'center'}}><Logo/><Link className="btn btn-secondary" to="/login">Entrar</Link></header>
<section className="hero"><div><span className="badge">Coordenação do cuidado materno-infantil</span><h1>Uma rede que conecta profissionais e dá continuidade ao cuidado.</h1><p>Indique com segurança, receba novas pacientes e compartilhe informações clínicas somente quando a paciente autorizar.</p><div className="row" style={{marginTop:24,flexWrap:'wrap'}}><a className="btn btn-primary" href="#planos">Conhecer os planos</a><a className="btn btn-secondary" href="#como-funciona">Como funciona</a></div></div><div className="hero-panel"><div className="card"><div className="muted">Rede Maternar</div><div className="metric">Cuidado conectado, sem perder a autonomia.</div><div className="grid grid-2" style={{marginTop:18}}><div className="card"><b>20%</b><div className="muted">Comissão por indicação convertida</div></div><div className="card"><b>1 prontuário</b><div className="muted">Acesso autorizado pela paciente</div></div></div></div></div></section>
<section className="section" id="como-funciona"><span className="badge">Como funciona</span><h2>Da indicação à continuidade do atendimento.</h2><div className="grid grid-4" style={{marginTop:28}}>{[['Entre na rede','Escolha o plano adequado à sua atuação.'],['Indique uma profissional','Envie a paciente por um link rastreável.'],['Acompanhe a conversão','Quando o atendimento for pago, a comissão é calculada.'],['Cuide em equipe','Com autorização, relatórios acompanham a jornada da paciente.']].map(([t,d],i)=><div className="card" key={t}><div className="badge">0{i+1}</div><h3>{t}</h3><p className="muted">{d}</p></div>)}</div></section>
<section className="section"><h2>Uma plataforma feita para o cuidado integrado.</h2><div className="grid grid-3" style={{marginTop:28}}>{[[Network,'Rede de indicações'],[CalendarDays,'Agenda integrada'],[MessageCircle,'Comunicação com pacientes'],[Wallet,'Pagamentos e comissões'],[ShieldCheck,'Consentimento e rastreabilidade'],[HeartHandshake,'Continuidade do cuidado']].map(([Icon,t])=><div className="card row" key={String(t)}><Icon size={26}/><b>{String(t)}</b></div>)}</div></section>
<section className="section" id="planos"><div className="center-heading"><span className="badge">Planos</span><h2>Comece gratuitamente ou ative toda a Rede Maternar.</h2><p className="muted">Sem mensalidade escondida. Escolha conforme a forma como deseja participar da rede.</p></div><div className="pricing-grid"><div className="pricing-card"><span className="badge">Plano Comunidade</span><h3>Gratuito</h3><div className="price">R$ 0</div><p className="muted">Para profissionais que desejam indicar e monetizar sua rede de confiança.</p>{free.map(x=><p className="feature" key={x}><Check size={18}/>{x}</p>)}<Link className="btn btn-secondary" to="/cadastro-profissional?plano=free">Criar cadastro gratuito</Link></div><div className="pricing-card featured"><span className="badge">Plano Anual</span><h3>Rede Maternar Completa</h3><div className="price">R$ 179,90/ano</div><p><strong>Em até 12x sem juros no cartão</strong></p><p className="muted">ou R$ 149,00 à vista no Pix ou boleto.</p>{annual.map(x=><p className="feature" key={x}><Check size={18}/>{x}</p>)}<Link className="btn btn-primary" to="/cadastro-profissional?plano=annual">Quero o Plano Anual</Link></div></div></section>
<section className="section"><div className="card" style={{background:'var(--wine)',color:'white',padding:36,textAlign:'center'}}><h2>Construa uma rede que cuida em conjunto.</h2><p style={{opacity:.85}}>A paciente permanece no controle de quem pode acessar suas informações.</p><a className="btn" style={{background:'white',color:'var(--wine)',display:'inline-block',marginTop:14}} href="#planos">Escolher meu plano</a></div></section></>}
