import { Link } from 'react-router-dom'
import { BarChart3, CalendarDays, Check, MessageCircle, Search, Users, Wallet } from 'lucide-react'
import { Logo } from '../../components/Logo'
import { LegalFooter } from './Legal'

const plans = [
  { name:'Marketplace Ilimitado', price:'R$ 59,90/ano', note:'Perfil profissional completo para ampliar sua presença e ser encontrada.', features:['Visitas e serviços ilimitados','Selo de perfil verificado','Destaque nas buscas','Relatório completo do perfil'], action:'Quero o Marketplace Ilimitado', plan:'marketplace' },
  { name:'Profissional Individual', price:'R$ 99,99/mês', note:'Marketplace + Sistema de Gestão e Vendas Completo (CRM + ERP).', features:['Marketplace Ilimitado incluso','Conta para uma profissional','Até 3 especialidades','CRM, agenda, WhatsApp e ERP financeiro'], action:'Quero minha gestão completa', plan:'independent', featured:true },
  { name:'Plano para Clínicas', price:'R$ 199,99/mês', note:'Marketplace + Sistema de Gestão e Vendas Completo (CRM + ERP).', features:['Cadastro de profissionais ilimitados','Especialidades ilimitadas','Agendas e repasses individuais','CRM, ERP e equipe com permissões'], action:'Quero gerenciar minha clínica', plan:'clinic', featured:false },
]

export function Landing() {
  return <div className="new-landing">
    <header className="public-header landing-header"><Logo/><nav><Link to="/profissionais">Encontrar profissionais</Link><a href="#gestao">CRM + ERP</a><a href="#planos">Planos</a></nav><Link className="btn btn-secondary" to="/login">Entrar</Link></header>
    <section className="hero new-hero"><div><span className="badge">Tecnologia para quem cuida</span><h1>Mais visibilidade. Mais organização. Mais tempo para atender.</h1><p>A MaterPlace reúne o marketplace especializado no cuidado materno-infantil com um CRM e ERP feito para a rotina da profissional.</p><div className="row hero-actions"><Link className="btn btn-primary" to="/cadastro-profissional?plano=marketplace">Criar meu cadastro</Link><a className="btn btn-secondary" href="#gestao">Conhecer a Gestão Completa</a></div><div className="trust-row"><span>✓ Cadastro verificado</span><span>✓ Foco materno-infantil</span><span>✓ Gestão em um só lugar</span></div></div><div className="product-preview"><div className="preview-top"><span>Visão geral</span><span className="badge">Gestão Completa</span></div><div className="preview-metrics"><div><small>Receita no mês</small><strong>R$ 12.480</strong><span>+18% no período</span></div><div><small>Oportunidades</small><strong>14</strong><span>5 novas hoje</span></div></div><div className="mini-pipeline">{['Novo contato','Em conversa','Agendado'].map((x,i)=><div key={x}><small>{x}</small><article><b>{['Juliana M.','Beatriz L.','Camila P.'][i]}</b><span>{['Marketplace','WhatsApp','Instagram'][i]}</span></article></div>)}</div></div></section>
    <section className="section marketplace-section" id="marketplace"><div><span className="badge">Marketplace especializado</span><h2>Seja encontrada por famílias que procuram exatamente o seu cuidado.</h2><p className="muted">Perfis completos, filtros por especialidade, cidade, modalidade e serviços. Uma experiência pensada para a jornada materno-infantil.</p><div className="feature-pills"><span><Search/>Busca inteligente</span><span><Users/>Perfil verificado</span><span><CalendarDays/>Solicitação de agenda</span></div><Link className="btn btn-primary" style={{display:'inline-flex',marginTop:22}} to="/profissionais">Explorar profissionais</Link></div><div className="market-card card"><div className="search-field"><Search/><span>Psicologia perinatal em São Paulo</span></div>{['Dra. Marina Lopes','Paula Nascimento','Camila Rocha'].map((name,i)=><div className="market-result" key={name}><div className="avatar">{name.split(' ').map(x=>x[0]).slice(0,2)}</div><div><strong>{name}</strong><small>{['Fonoaudiologia','Doula e educadora perinatal','Pediatria'][i]}</small></div><span className="availability-badge">Disponível</span></div>)}</div></section>
    <section className="section management-section" id="gestao"><div className="center-heading"><span className="badge">CRM + ERP</span><h2>Do primeiro contato ao fechamento do mês.</h2><p className="muted">Centralize a operação sem perder a leveza da sua rotina.</p></div><div className="grid grid-3">{[
      [Users,'CRM e funil','Organize contatos, oportunidades, retornos e histórico comercial.'],
      [MessageCircle,'WhatsApp Business','Receba e responda conversas na central de atendimento.'],
      [CalendarDays,'Agenda inteligente','Controle horários, confirmações, bloqueios e lembretes.'],
      [Wallet,'Financeiro ERP','Receitas, despesas, fluxo de caixa e contas a receber.'],
      [BarChart3,'Relatórios','Acompanhe conversão, ocupação, origem e desempenho.'],
      [Search,'Marketplace integrado','Seu catálogo e disponibilidade alimentam o perfil público.'],
    ].map(([Icon,title,copy])=><article className="card feature-card" key={String(title)}><div className="metric-icon"><Icon/></div><h3>{String(title)}</h3><p className="muted">{String(copy)}</p></article>)}</div></section>
    <section className="section" id="planos"><div className="center-heading"><span className="badge">Planos transparentes</span><h2>Escolha a solução ideal para o seu momento.</h2></div><div className="pricing-grid pricing-grid-3">{plans.map(plan=><article className={`pricing-card ${plan.featured?'featured':''}`} key={plan.name}>{plan.featured&&<span className="plan-ribbon">Melhor custo-benefício</span>}<h3>{plan.name}</h3><div className="price">{plan.price}</div><p className="muted">{plan.note}</p>{plan.features.map(x=><p className="feature" key={x}><Check size={18}/>{x}</p>)}<Link className={`btn ${plan.featured?'btn-primary':'btn-secondary'}`} to={`/cadastro-profissional?plano=${plan.plan}`}>{plan.action}</Link></article>)}</div></section>
    <LegalFooter/>
  </div>
}
