import { Link } from 'react-router-dom'
import { Logo } from '../../components/Logo'

const contact='jessica.calegari7@gmail.com'
export function PrivacyPolicy(){return <Legal title="Política de Privacidade"><p>A MaterPlace trata dados cadastrais para oferecer marketplace, CRM e ERP às organizações contratantes.</p><h2>Dados e finalidades</h2><p>Podemos tratar nome, e-mail, telefone, dados profissionais, agenda e informações administrativas e financeiras para executar o serviço, cumprir obrigações, prevenir fraude e atender o titular.</p><h2>Compartilhamento</h2><p>Fornecedores de infraestrutura, autenticação, comunicação e pagamentos podem processar dados dentro da finalidade contratada. Não vendemos dados pessoais.</p><h2>Direitos e segurança</h2><p>O titular pode solicitar acesso, correção, eliminação quando aplicável e informações pelo e-mail {contact}. Usamos autenticação e isolamento por organização.</p></Legal>}
export function TermsOfUse(){return <Legal title="Termos de Uso"><p>A plataforma oferece divulgação e gestão; não substitui orientação médica, diagnóstico ou atendimento de emergência.</p><h2>Responsabilidades</h2><p>Profissionais e clínicas respondem pela veracidade de registros, serviços, preços, agenda e informações inseridas.</p><h2>Integrações</h2><p>Pagamentos, mensagens, notas fiscais e videoconferência dependem de contratação e aprovação dos respectivos parceiros.</p><h2>Uso permitido</h2><p>É proibido usar a plataforma para fraude, spam, conteúdo ilegal ou acesso indevido.</p></Legal>}
export function LgpdPage(){return <Legal title="LGPD e Direitos do Titular"><p>A MaterPlace observa finalidade, necessidade, transparência, segurança e prestação de contas da Lei nº 13.709/2018.</p><h2>Papéis</h2><p>Cada clínica ou profissional é responsável pelos dados de suas pacientes. A MaterPlace atua conforme o contexto como controladora dos cadastros e operadora dos dados das organizações.</p><h2>Solicitações</h2><p>Envie nome, e-mail usado e o direito desejado para {contact}. A identidade poderá ser confirmada antes da resposta.</p></Legal>}
export function AboutPage(){return <Legal title="Sobre a MaterPlace"><p>A MaterPlace é um ecossistema materno-infantil que conecta famílias, profissionais e informação confiável.</p><h2>Missão e compromisso editorial</h2><p>Nossa missão é ampliar o acesso a apoio qualificado. Produzimos conteúdo original, identificamos autores e datas, consultamos fontes confiáveis e corrigimos informações quando necessário.</p><h2>Transparência</h2><p>Conteúdo editorial, publicidade e perfis profissionais são apresentados de forma distinta. Informações educativas não substituem avaliação individual.</p></Legal>}
export function DisclaimerPage(){return <Legal title="Isenção de Responsabilidade"><p>Os conteúdos têm finalidade educativa e não constituem diagnóstico, prescrição ou aconselhamento médico individual.</p><h2>Links e profissionais</h2><p>Serviços, opiniões e links externos são de responsabilidade de seus autores e prestadores. Em emergência, procure imediatamente um serviço de saúde.</p></Legal>}
export function ContactPage(){return <Legal title="Contato"><p><strong>E-mail institucional:</strong> <a href={`mailto:${contact}`}>{contact}</a></p><p>Tempo médio de resposta: até 48 horas úteis.</p><form className="contact-form" action={`mailto:${contact}`} method="post" encType="text/plain"><label>Nome<input name="nome" required/></label><label>E-mail<input name="email" type="email" required/></label><label>Assunto<input name="assunto" required/></label><label>Mensagem<textarea name="mensagem" rows={6} required/></label><button className="btn btn-primary">Enviar mensagem</button></form></Legal>}
export function CookiePolicy(){return <Legal title="Política de Cookies"><p>Usamos cookies essenciais para autenticação e segurança. Métricas ou publicidade só deverão ser ativadas com configuração adequada de consentimento.</p><p>Cookies podem ser controlados no navegador, mas desativar os essenciais pode impedir o login.</p></Legal>}
function Legal({title,children}:{title:string;children:React.ReactNode}){return <div className="legal-page"><header className="public-header"><Link to="/"><Logo/></Link><Link className="btn btn-secondary" to="/">Voltar ao início</Link></header><main className="card legal-card"><h1>{title}</h1><p className="muted">Última atualização: 5 de agosto de 2026.</p>{children}<p className="muted">Base operacional sujeita à revisão jurídica antes do lançamento comercial definitivo.</p></main><LegalFooter/></div>}
export function LegalFooter(){return <footer className="landing-footer"><Logo/><nav><Link to="/sobre">Sobre nós</Link><Link to="/privacidade">Privacidade</Link><Link to="/termos">Termos</Link><Link to="/lgpd">LGPD</Link><Link to="/isencao-de-responsabilidade">Isenção</Link><Link to="/cookies">Cookies</Link><Link to="/contato">Contato</Link></nav><span>© 2026 MaterPlace</span></footer>}
