import { Link } from 'react-router-dom'
import { Logo } from '../../components/Logo'
import { useEffect, useState } from 'react'
import { defaultEditorialStaff, getEditorialStaff } from '../../lib/portalSettings'
import { Seo } from '../../components/Seo'

const contact='jessica.calegari7@gmail.com'
export function PrivacyPolicy(){return <Legal title="Política de Privacidade"><p>A MaterPlace trata dados pessoais conforme a LGPD e adota medidas de segurança e transparência.</p><h2>Dados coletados e finalidades</h2><p>Podemos coletar nome, e-mail, telefone e informações enviadas em formulários, newsletter e cadastros; dados profissionais, agenda e informações administrativas; além de endereço IP, navegador, páginas acessadas e cookies do Google Analytics e, quando ativado com consentimento aplicável, do Google AdSense. Usamos esses dados para prestar o serviço, responder solicitações, medir audiência, melhorar o portal, prevenir fraude e exibir publicidade.</p><h2>Cookies de publicidade, Google e DART</h2><p>Fornecedores terceirizados, incluindo o Google, usam cookies para veicular anúncios com base em visitas anteriores a este e a outros sites. O cookie DART e tecnologias semelhantes podem ser usados para personalização e medição. Redes e parceiros de publicidade podem coletar dados de navegação para selecionar, medir e personalizar anúncios.</p><p>O usuário pode gerenciar a publicidade personalizada nas <a href="https://www.google.com/settings/ads" target="_blank" rel="noreferrer">Configurações de Anúncios do Google</a> e consultar opções adicionais na <a href="https://www.aboutads.info/choices" target="_blank" rel="noreferrer">Network Advertising Initiative</a>. Também pode bloquear ou apagar cookies no navegador.</p><h2>Compartilhamento e retenção</h2><p>Fornecedores de infraestrutura, autenticação, análise, comunicação, publicidade e pagamentos podem processar dados somente para as finalidades contratadas ou exigências legais. A MaterPlace não vende dados pessoais.</p><h2>Direitos do titular</h2><p>O titular pode solicitar confirmação, acesso, correção, informação sobre compartilhamento, oposição, revogação de consentimento ou exclusão nos casos previstos em lei. Solicitações devem ser enviadas para <a href={`mailto:${contact}`}>{contact}</a>.</p></Legal>}
export function TermsOfUse(){return <Legal title="Termos de Uso"><p>A plataforma oferece divulgação e gestão; não substitui orientação médica, diagnóstico ou atendimento de emergência.</p><h2>Responsabilidades</h2><p>Profissionais e clínicas respondem pela veracidade de registros, serviços, preços, agenda e informações inseridas.</p><h2>Integrações</h2><p>Pagamentos, mensagens, notas fiscais e videoconferência dependem de contratação e aprovação dos respectivos parceiros.</p><h2>Uso permitido</h2><p>É proibido usar a plataforma para fraude, spam, conteúdo ilegal ou acesso indevido.</p></Legal>}
export function LgpdPage(){return <Legal title="LGPD e Direitos do Titular"><p>A MaterPlace observa finalidade, necessidade, transparência, segurança e prestação de contas da Lei nº 13.709/2018.</p><h2>Papéis</h2><p>Cada clínica ou profissional é responsável pelos dados de suas pacientes. A MaterPlace atua conforme o contexto como controladora dos cadastros e operadora dos dados das organizações.</p><h2>Solicitações</h2><p>Envie nome, e-mail usado e o direito desejado para {contact}. A identidade poderá ser confirmada antes da resposta.</p></Legal>}
export function AboutPage(){return <Legal title="Sobre a MaterPlace"><p>A MaterPlace é um ecossistema materno-infantil que conecta famílias, profissionais e informação confiável.</p><h2>Missão e compromisso editorial</h2><p>Nossa missão é ampliar o acesso a apoio qualificado. Produzimos conteúdo original, identificamos autores e datas, consultamos fontes confiáveis e corrigimos informações quando necessário.</p><h2>Transparência</h2><p>Conteúdo editorial, publicidade e perfis profissionais são apresentados de forma distinta. Informações educativas não substituem avaliação individual.</p></Legal>}
export function DisclaimerPage(){return <Legal title="Isenção de Responsabilidade"><p>Os conteúdos têm finalidade educativa e não constituem diagnóstico, prescrição ou aconselhamento médico individual.</p><h2>Links e profissionais</h2><p>Serviços, opiniões e links externos são de responsabilidade de seus autores e prestadores. Em emergência, procure imediatamente um serviço de saúde.</p></Legal>}
export function ContactPage(){return <Legal title="Contato"><p><strong>E-mail institucional:</strong> <a href={`mailto:${contact}`}>{contact}</a></p><p>Tempo médio de resposta: até 48 horas úteis.</p><form className="contact-form" action={`mailto:${contact}`} method="post" encType="text/plain"><label>Nome<input name="nome" required/></label><label>E-mail<input name="email" type="email" required/></label><label>Assunto<input name="assunto" required/></label><label>Mensagem<textarea name="mensagem" rows={6} required/></label><button className="btn btn-primary">Enviar mensagem</button></form></Legal>}
export function CookiePolicy(){return <Legal title="Política de Cookies"><p>Usamos cookies essenciais para autenticação e segurança. Métricas ou publicidade só deverão ser ativadas com configuração adequada de consentimento.</p><p>Cookies podem ser controlados no navegador, mas desativar os essenciais pode impedir o login.</p></Legal>}
export function EditorialStaffPage(){const[staff,setStaff]=useState(defaultEditorialStaff);useEffect(()=>{getEditorialStaff().then(setStaff).catch(()=>undefined)},[]);return <Legal title="Expediente"><h2>Responsabilidade editorial</h2><p><strong>Jornalista responsável:</strong> {staff.responsibleJournalist}</p><p><strong>Consultora técnica em amamentação:</strong> {staff.technicalConsultant}</p><h2>Compromisso</h2><p>O conteúdo editorial da MaterPlace é produzido e revisado com transparência, identificação de autoria e consulta a fontes confiáveis. Conteúdos educativos não substituem avaliação individual por profissional habilitado.</p></Legal>}
const legalDescriptions:Record<string,string>={
  'Política de Privacidade':'Saiba como a MaterPlace coleta, utiliza e protege dados pessoais e como exercer seus direitos.',
  'Termos de Uso':'Consulte as condições de uso, responsabilidades e regras aplicáveis à plataforma MaterPlace.',
  'LGPD e Direitos do Titular':'Conheça os direitos previstos na LGPD e os canais de atendimento da MaterPlace.',
  'Sobre a MaterPlace':'Conheça a missão, o compromisso editorial e os princípios de transparência da MaterPlace.',
  'Isenção de Responsabilidade':'Entenda os limites do conteúdo educativo e das informações profissionais publicadas na MaterPlace.',
  'Contato':'Entre em contato com a equipe MaterPlace.',
  'Política de Cookies':'Saiba como a MaterPlace utiliza cookies essenciais, métricas e publicidade.',
  'Expediente':'Conheça a responsabilidade editorial e técnica do conteúdo publicado pela MaterPlace.',
}
function Legal({title,children}:{title:string;children:React.ReactNode}){const description=legalDescriptions[title]||`${title} da MaterPlace.`;return <div className="legal-page"><Seo title={title} description={description}/><header className="public-header"><Link to="/"><Logo/></Link><Link className="btn btn-secondary" to="/">Voltar ao início</Link></header><main className="card legal-card"><h1>{title}</h1><p className="muted">Última atualização: 1º de setembro de 2026.</p>{children}</main><LegalFooter/></div>}
export function LegalFooter(){return <footer className="landing-footer"><Link to="/" aria-label="MaterPlace — voltar ao início"><Logo/></Link><nav><Link to="/sobre">Sobre nós</Link><Link to="/expediente">Expediente</Link><Link to="/privacidade">Privacidade</Link><Link to="/termos">Termos</Link><Link to="/lgpd">LGPD</Link><Link to="/isencao-de-responsabilidade">Isenção</Link><Link to="/cookies">Cookies</Link><Link to="/contato">Contato</Link></nav><span>© 2026 MaterPlace</span></footer>}
