import { Link } from 'react-router-dom'
import { Logo } from '../../components/Logo'

const contact='jessica.calegari7@gmail.com'
export function PrivacyPolicy(){return <Legal title="Política de Privacidade"><p>A Rede Maternar trata dados cadastrais para oferecer marketplace, CRM e ERP às organizações contratantes.</p><h2>Dados e finalidades</h2><p>Podemos tratar nome, e-mail, telefone, dados profissionais, agenda e informações administrativas e financeiras para executar o serviço, cumprir obrigações, prevenir fraude e atender o titular.</p><h2>Compartilhamento</h2><p>Fornecedores de infraestrutura, autenticação, comunicação e pagamentos podem processar dados dentro da finalidade contratada. Não vendemos dados pessoais.</p><h2>Direitos e segurança</h2><p>O titular pode solicitar acesso, correção, eliminação quando aplicável e informações pelo e-mail {contact}. Usamos autenticação e isolamento por organização.</p></Legal>}
export function TermsOfUse(){return <Legal title="Termos de Uso"><p>A plataforma oferece divulgação e gestão; não substitui orientação médica, diagnóstico ou atendimento de emergência.</p><h2>Responsabilidades</h2><p>Profissionais e clínicas respondem pela veracidade de registros, serviços, preços, agenda e informações inseridas.</p><h2>Integrações</h2><p>Pagamentos, mensagens, notas fiscais e videoconferência dependem de contratação e aprovação dos respectivos parceiros.</p><h2>Uso permitido</h2><p>É proibido usar a plataforma para fraude, spam, conteúdo ilegal ou acesso indevido.</p></Legal>}
export function LgpdPage(){return <Legal title="LGPD e Direitos do Titular"><p>A Rede Maternar observa finalidade, necessidade, transparência, segurança e prestação de contas da Lei nº 13.709/2018.</p><h2>Papéis</h2><p>Cada clínica ou profissional é responsável pelos dados de suas pacientes. A Rede Maternar atua conforme o contexto como controladora dos cadastros e operadora dos dados das organizações.</p><h2>Solicitações</h2><p>Envie nome, e-mail usado e o direito desejado para {contact}. A identidade poderá ser confirmada antes da resposta.</p></Legal>}
export function ContactPage(){return <Legal title="Contato"><p>Suporte, privacidade, LGPD e parcerias:</p><p><strong>E-mail:</strong> <a href={`mailto:${contact}`}>{contact}</a></p></Legal>}
export function CookiePolicy(){return <Legal title="Política de Cookies"><p>Usamos cookies essenciais para autenticação e segurança. Métricas ou publicidade só deverão ser ativadas com configuração adequada de consentimento.</p><p>Cookies podem ser controlados no navegador, mas desativar os essenciais pode impedir o login.</p></Legal>}
function Legal({title,children}:{title:string;children:React.ReactNode}){return <div className="legal-page"><header className="public-header"><Link to="/"><Logo/></Link><Link className="btn btn-secondary" to="/">Voltar ao início</Link></header><main className="card legal-card"><h1>{title}</h1><p className="muted">Última atualização: 5 de agosto de 2026.</p>{children}<p className="muted">Base operacional sujeita à revisão jurídica antes do lançamento comercial definitivo.</p></main><LegalFooter/></div>}
export function LegalFooter(){return <footer className="landing-footer"><Logo/><nav><Link to="/privacidade">Privacidade</Link><Link to="/termos">Termos</Link><Link to="/lgpd">LGPD</Link><Link to="/cookies">Cookies</Link><Link to="/contato">Contato</Link></nav><span>© 2026 Rede Maternar</span></footer>}
