import { useMemo, useState } from 'react'
import { CheckCircle2, ChevronDown, MapPin, MessageCircle, Search, SlidersHorizontal, Star } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Logo } from '../../components/Logo'

const professionals = [
  {slug:'marina-lopes',name:'Marina Lopes',specialty:'Fonoaudióloga materno-infantil',registration:'CRFa 2-12345',city:'São Paulo, SP',neighborhood:'Moema',rating:4.9,reviews:87,mode:'Presencial e online',price:'A partir de R$ 180',available:'Hoje',initials:'ML',tone:'rose',services:['Amamentação','Motricidade oral','Introdução alimentar']},
  {slug:'paula-nascimento',name:'Paula Nascimento',specialty:'Doula e educadora perinatal',registration:'Certificação verificada',city:'São Paulo, SP',neighborhood:'Vila Mariana',rating:5.0,reviews:42,mode:'Presencial e online',price:'A partir de R$ 150',available:'Amanhã',initials:'PN',tone:'gold',services:['Pré-natal','Plano de parto','Pós-parto']},
  {slug:'camila-rocha',name:'Camila Rocha',specialty:'Pediatra',registration:'CRM-SP 123456 · RQE 98765',city:'São Paulo, SP',neighborhood:'Pinheiros',rating:4.8,reviews:126,mode:'Presencial',price:'A partir de R$ 320',available:'Qui, 14:00',initials:'CR',tone:'wine',services:['Puericultura','Consulta pediátrica','Sono infantil']},
  {slug:'fernanda-alves',name:'Fernanda Alves',specialty:'Psicóloga perinatal',registration:'CRP 06/123456',city:'Campinas, SP',neighborhood:'Cambuí',rating:4.9,reviews:64,mode:'Online',price:'A partir de R$ 190',available:'Hoje',initials:'FA',tone:'sage',services:['Gestação','Puerpério','Luto perinatal']},
  {slug:'larissa-souza',name:'Larissa Souza',specialty:'Nutricionista materno-infantil',registration:'CRN-3 54321',city:'Santos, SP',neighborhood:'Gonzaga',rating:4.7,reviews:38,mode:'Presencial e online',price:'A partir de R$ 210',available:'Sex, 09:00',initials:'LS',tone:'blue',services:['Gestação','Amamentação','Introdução alimentar']},
]

export function Marketplace(){
  const [query,setQuery]=useState('')
  const [city,setCity]=useState('')
  const [mode,setMode]=useState('Todos')
  const visible=useMemo(()=>professionals.filter(p=>{
    const hay=`${p.name} ${p.specialty} ${p.services.join(' ')} ${p.city} ${p.neighborhood}`.toLowerCase()
    return hay.includes(query.toLowerCase())&&(!city||`${p.city} ${p.neighborhood}`.toLowerCase().includes(city.toLowerCase()))&&(mode==='Todos'||p.mode.includes(mode))
  }),[query,city,mode])
  function trackWhatsApp(name:string){
    const key='rede-maternar:whatsapp-clicks'
    const current=JSON.parse(localStorage.getItem(key)||'[]') as unknown[]
    localStorage.setItem(key,JSON.stringify([...current,{professional:name,at:new Date().toISOString(),source:'marketplace'}]))
    alert(`Clique registrado para ${name}. Na versão real, o WhatsApp da profissional será aberto com a origem “Rede Maternar”.`)
  }
  return <div className="marketplace-page"><header className="public-header marketplace-header"><Link to="/"><Logo/></Link><nav><Link to="/">Início</Link><a href="#como-funciona">Como funciona</a><Link to="/cadastro-profissional">Sou profissional</Link></nav><Link className="btn btn-secondary" to="/login">Entrar</Link></header>
    <section className="marketplace-search-hero"><div><span className="badge">Profissionais materno-infantis</span><h1>Encontre a profissional certa para o seu momento.</h1><p>Pesquise por especialidade, serviço ou localização. Veja avaliações e converse diretamente pelo WhatsApp.</p></div><div className="marketplace-search-box"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Especialidade, serviço ou nome"/></label><label><MapPin/><input value={city} onChange={e=>setCity(e.target.value)} placeholder="Cidade ou bairro"/></label><button className="btn btn-primary">Buscar</button></div></section>
    <main className="marketplace-results-shell"><aside className="marketplace-filters card"><div className="row"><SlidersHorizontal/><h3>Filtros</h3></div><label>Modalidade<select value={mode} onChange={e=>setMode(e.target.value)}><option>Todos</option><option>Presencial</option><option>Online</option></select></label><label>Disponibilidade<select><option>Qualquer data</option><option>Hoje</option><option>Próximos 3 dias</option></select></label><label>Faixa de preço<select><option>Todos os valores</option><option>Até R$ 200</option><option>R$ 200 a R$ 300</option></select></label><label className="check-filter"><input type="checkbox"/> Somente perfis verificados</label><p className="privacy-note"><MapPin/>A Rede Maternar exibe somente o bairro. O endereço completo é compartilhado diretamente pela profissional.</p></aside>
      <section className="marketplace-list"><div className="results-head"><div><h2>{visible.length} profissionais encontradas</h2><p className="muted">Perfis individuais verificados pela Rede Maternar.</p></div><button className="sort-button">Mais relevantes <ChevronDown/></button></div>{visible.map(p=><article className="professional-result-card" key={p.slug}><div className={`professional-photo ${p.tone}`}>{p.initials}</div><div className="professional-result-main"><div className="verified-name"><h2>{p.name}</h2><CheckCircle2/><span>Verificada</span></div><h3>{p.specialty}</h3><p className="registration">{p.registration}</p><div className="rating-line"><Star fill="currentColor"/><strong>{p.rating.toFixed(1)}</strong><a href="#avaliacoes">{p.reviews} avaliações</a></div><div className="location-line"><MapPin/><span>{p.neighborhood} · {p.city}</span><span>Endereço protegido</span></div><div className="service-tags">{p.services.map(x=><span key={x}>{x}</span>)}</div></div><aside className="professional-result-action"><span className="availability-dot">● Próximo horário</span><strong>{p.available}</strong><small>{p.mode}</small><b>{p.price}</b><button className="btn whatsapp-btn" onClick={()=>trackWhatsApp(p.name)}><MessageCircle/> Falar no WhatsApp</button><Link className="btn btn-secondary" to={`/perfil/${p.slug}`}>Ver perfil completo</Link></aside></article>)}{visible.length===0&&<div className="card empty-state"><Search/><h3>Nenhuma profissional encontrada</h3><p className="muted">Tente retirar algum filtro ou buscar por outra especialidade.</p></div>}</section>
    </main><section className="marketplace-how" id="como-funciona"><h2>Escolha com informação e privacidade.</h2><div>{[['1','Busque','Filtre por especialidade, serviço, cidade ou bairro.'],['2','Compare','Veja perfil, formação, serviços e avaliações.'],['3','Converse','Fale diretamente pelo WhatsApp da profissional.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section><footer className="landing-footer"><Logo/><span>Ambiente demonstrativo · contatos e avaliações fictícios</span></footer>
  </div>
}
