import { FormEvent, useEffect, useState } from 'react'
import { BadgeCheck, CheckCircle2, Clock3, CreditCard, Crown, ExternalLink, Instagram, MapPin, Send, Star } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { Logo } from '../../components/Logo'
import { getMarketplaceProfessional, listProfessionalReviews, listPublicServices, recordProfessionalProfileView, submitProfessionalReview } from '../../lib/operations'
import { LegalFooter } from './Legal'

export function PublicProfessionalProfile() {
  const {slug=''}=useParams(); const [profile,setProfile]=useState<any>(); const [services,setServices]=useState<any[]>([]); const [reviews,setReviews]=useState<any[]>([]); const [loaded,setLoaded]=useState(false); const [reviewNotice,setReviewNotice]=useState(''); const [reviewError,setReviewError]=useState('')
  async function loadProfile(){const p=await getMarketplaceProfessional(slug);setProfile(p);if(p){await recordProfessionalProfileView(p.id);const [serviceRows,reviewRows]=await Promise.all([listPublicServices(p.id),listProfessionalReviews(p.id)]);setServices(serviceRows);setReviews(reviewRows)}}
  useEffect(()=>{void loadProfile().finally(()=>setLoaded(true))},[slug])
  async function submitReview(event:FormEvent<HTMLFormElement>){event.preventDefault();setReviewError('');setReviewNotice('');const form=event.currentTarget;const fields=new FormData(form);try{await submitProfessionalReview({professionalId:profile.id,name:String(fields.get('name')||''),email:String(fields.get('email')||''),rating:Number(fields.get('rating')||0),comment:String(fields.get('comment')||'')});setReviewNotice('Avaliação publicada. Obrigada por compartilhar sua experiência.');form.reset();const updated=await getMarketplaceProfessional(slug);setProfile(updated);setReviews(await listProfessionalReviews(profile.id))}catch(error){setReviewError(error instanceof Error?error.message:'Não foi possível enviar a avaliação.')}}
  if(!loaded)return <div className="auth-page"><div className="auth-card">Carregando perfil...</div></div>
  if(!profile)return <div className="auth-page"><div className="auth-card"><Logo/><h1>Perfil não encontrado</h1><p>O perfil não está publicado ou não existe.</p><Link className="btn btn-primary" to="/profissionais">Voltar à busca</Link></div></div>
  const whats=String(profile.whatsapp||'').replace(/\D/g,'')
  const premium=profile.plan&&profile.plan!=='free'
  const instagramUrl=profile.instagram_handle&&(profile.instagram_handle.startsWith('http')?profile.instagram_handle:`https://instagram.com/${profile.instagram_handle.replace('@','')}`)
  const safeText=(value:unknown)=>typeof value==='string'?value:''
  const openingHours=safeText(profile.opening_hours)
  return <div className="clinic-profile-page">
    <header className="portal-topbar compact"><Link to="/"><Logo/></Link><Link className="btn btn-secondary" to="/login">Profissional de Saúde</Link></header>
    <main className="clinic-profile-shell">
      <section className="clinic-cover"><div className="clinic-cover-media">{profile.cover_image_url&&<img src={profile.cover_image_url} alt={`Capa de ${profile.clinic_name||profile.full_name}`} width="1600" height="560" fetchPriority="high"/>}</div><div className="clinic-profile-main"><div className="clinic-logo">{profile.profile_image_url?<img src={profile.profile_image_url} alt={`Foto de ${profile.full_name}`} width="160" height="160"/>:profile.full_name.split(' ').slice(0,2).map((x:string)=>x[0]).join('')}</div><div className="clinic-identity">
        <div className="profile-status-row">{premium&&<span className="premium-profile-badge"><Crown/> Perfil Premium</span>}{profile.verified&&<span className="verified-profile-badge"><BadgeCheck/> Perfil verificado</span>}</div><h1>{profile.full_name}{profile.verified&&<CheckCircle2/>}</h1>{profile.clinic_name&&<strong>{profile.clinic_name}</strong>}
        <p>{safeText(profile.bio)||'Perfil profissional cadastrado na MaterPlace.'}</p>
        <div className="clinic-rating"><strong>{Number(profile.rating).toFixed(1)}</strong><Star fill="currentColor"/><span>({profile.review_count} avaliações)</span></div>
        <div className="service-tags">{profile.specialties.map((x:string)=><span key={x}>{x}</span>)}</div>
      </div></div>
      <div className="clinic-contact-grid"><div><MapPin/><span><b>Localização</b><strong>{[profile.neighborhood,profile.city,profile.state_code].filter(Boolean).join(' · ')}</strong></span></div><div><Clock3/><span><b>Atendimento</b><strong>{profile.accepts_online?'Presencial e online':'Presencial'}</strong></span></div></div>
      {(whats||instagramUrl)&&<div className="clinic-cta-row">{whats&&<a className="btn btn-primary whatsapp" href={`https://wa.me/${whats}`} target="_blank" rel="noreferrer">Falar no WhatsApp</a>}{instagramUrl&&<a className="btn instagram" href={instagramUrl} target="_blank" rel="noreferrer"><Instagram/> Ver perfil no Instagram</a>}</div>}
      </section>
      <section className="clinic-info-grid"><article><h2>Sobre</h2><p>{safeText(profile.clinic_description)||safeText(profile.bio)||'Informações em atualização.'}</p>{openingHours&&<p><strong>Horários:</strong> {openingHours}</p>}<div className="profile-social-links">{profile.website_url&&<a href={profile.website_url} target="_blank" rel="noreferrer"><ExternalLink/>Site</a>}{profile.instagram_handle&&<a href={profile.instagram_handle.startsWith('http')?profile.instagram_handle:`https://instagram.com/${profile.instagram_handle.replace('@','')}`} target="_blank" rel="noreferrer">Instagram</a>}{profile.facebook_url&&<a href={profile.facebook_url} target="_blank" rel="noreferrer">Facebook</a>}{profile.tiktok_url&&<a href={profile.tiktok_url} target="_blank" rel="noreferrer">TikTok</a>}</div></article><article><h2><CreditCard/> Formas de pagamento</h2>{profile.payment_methods.length?profile.payment_methods.map((x:string)=><p key={x}>{x}</p>):<p>Consulte a profissional.</p>}</article><article><h2>Convênios</h2>{profile.accepted_insurances.length?profile.accepted_insurances.map((x:string)=><p key={x}>{x}</p>):<p>Atendimento particular ou informação não cadastrada.</p>}</article></section>
      <section className="clinic-section-card premium-services-section"><div className="premium-section-heading"><span>Experiência personalizada</span><h2>Serviços oferecidos</h2><p>Conheça os atendimentos disponíveis e escolha o cuidado ideal para você.</p></div>{services.length?<div className="clinic-service-cards">{services.map((s,index)=><article key={s.id}><span className="service-card-number">{String(index+1).padStart(2,'0')}</span><h3>{s.name}</h3><p>{s.description||s.specialty||'Serviço profissional'}</p>{s.professional_name&&<strong>{s.professional_name} {s.professional_registration&&`· ${s.professional_registration}`}</strong>}<footer><small>{s.duration_minutes} min · {(s.attendance_modes||[]).join(', ')}</small><b>{(s.price_cents/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</b></footer></article>)}</div>:<p>Nenhum serviço publicado.</p>}</section>
      <section className="clinic-reviews public-review-section"><div className="review-summary"><strong>{Number(profile.rating||0).toFixed(1)}</strong><span>{[1,2,3,4,5].map(i=><Star key={i} fill="currentColor"/>)}</span><small>{profile.review_count||0} avaliações</small></div><div className="review-list"><h2>Avaliações</h2>{reviews.slice(0,4).map(review=><article key={review.id}><span>{Array.from({length:review.rating},(_,i)=><Star key={i} fill="currentColor"/>)}</span><p>{review.comment||'A pessoa avaliou este atendimento.'}</p><small>{review.reviewer_name} · {new Date(review.created_at).toLocaleDateString('pt-BR')}</small></article>)}{!reviews.length&&<p className="muted">Seja a primeira pessoa a avaliar este perfil.</p>}</div><form className="public-review-form" onSubmit={submitReview}><h2>Avalie esta profissional</h2><p>Informe seus dados e compartilhe sua experiência.</p><label><span>Seu nome</span><input name="name" required minLength={2}/></label><label><span>Seu e-mail</span><input name="email" type="email" required/></label><label><span>Sua nota</span><select name="rating" required defaultValue=""><option value="" disabled>Escolha de 1 a 5</option><option value="5">5 — Excelente</option><option value="4">4 — Muito bom</option><option value="3">3 — Bom</option><option value="2">2 — Regular</option><option value="1">1 — Ruim</option></select></label><label><span>Comentário (opcional)</span><textarea name="comment" maxLength={1000} rows={3}/></label>{reviewError&&<div className="alert alert-error">{reviewError}</div>}{reviewNotice&&<div className="alert alert-success">{reviewNotice}</div>}<button className="btn btn-primary"><Send/> Publicar avaliação</button></form></section>
      {(profile.office_video_urls?.length>0||profile.office_video_url)&&<section className="clinic-section-card"><h2>Vídeos da clínica</h2><div className="clinic-videos">{(profile.office_video_urls?.length?profile.office_video_urls:[profile.office_video_url]).filter(Boolean).map((url:string)=><video key={url} controls preload="metadata" src={url}/>)}</div></section>}
      {profile.gallery_urls?.length>0&&<section className="clinic-section-card"><h2>Fotos da clínica</h2><div className="clinic-gallery">{profile.gallery_urls.map((url:string)=><img key={url} src={url} alt={`Ambiente de ${profile.clinic_name||profile.full_name}`} loading="lazy" width="480" height="320"/>)}</div></section>}
    </main><LegalFooter/>
  </div>
}
