import { LocalRepository } from '../../repositories/storage'
import type { AuditLog, MedicalRecord, RecordConsent, TimelineEntry } from './domain'
const records=new LocalRepository<MedicalRecord>('rm:v08:records',[{id:'record-1',patientId:'patient-1',patientData:{nome:'Camila Ribeiro',cidade:'São Paulo'},babyData:{nome:'Clara',nascimento:'2026-05-12'},pregnancy:{acompanhamento:'Pré-natal concluído'},birth:{tipo:'Informado pela paciente'},contacts:[{name:'Rafael Ribeiro',relationship:'Companheiro',phone:'(11) 99999-1000'}],relevantInformation:['Cuidado integrado autorizado pela paciente.']}])
const timeline=new LocalRepository<TimelineEntry>('rm:v08:timeline',[{id:'timeline-1',medicalRecordId:'record-1',authorId:'professional-1',authorRole:'professional',specialty:'Fonoaudiologia',type:'evolution',content:'Avaliação inicial realizada; continuidade do cuidado indicada.',attachmentIds:[],visibility:'patient_and_authorized',createdAt:'2026-07-28T13:00:00.000Z',version:1}])
const consents=new LocalRepository<RecordConsent>('rm:v08:consents',[{id:'consent-1',patientId:'patient-1',professionalId:'professional-1',grantedById:'patient-1',scopes:['full'],selectedEntryIds:[],startsAt:'2026-07-28T12:00:00.000Z',endsWithCare:false}])
const audits=new LocalRepository<AuditLog>('rm:v08:audit',[])
function log(value:Omit<AuditLog,'id'|'occurredAt'>){audits.save({...value,id:crypto.randomUUID(),occurredAt:new Date().toISOString()})}
export function consentStatus(value:RecordConsent,at=new Date()){if(value.revokedAt)return'revoked';if(value.expiresAt&&new Date(value.expiresAt)<=at)return'expired';return'active'}
export function canAccessRecord(patientId:string,professionalId:string){return consents.list().some(value=>value.patientId===patientId&&value.professionalId===professionalId&&consentStatus(value)==='active')}
export function getMedicalRecord(patientId:string,viewer:{id:string;role:string}){if(viewer.role==='professional'&&!canAccessRecord(patientId,viewer.id))throw new Error('Acesso ao prontuário não autorizado.');const record=records.list().find(value=>value.patientId===patientId);if(!record)throw new Error('Prontuário não encontrado.');log({actorId:viewer.id,actorRole:viewer.role,action:'access',resource:'medical_record',resourceId:record.id,metadata:{patientId}});return{record,timeline:timeline.list().filter(value=>value.medicalRecordId===record.id),consents:consents.list().filter(value=>value.patientId===patientId)}}
export function appendEntry(input:Omit<TimelineEntry,'id'|'createdAt'|'version'>){const entry={...input,id:crypto.randomUUID(),createdAt:new Date().toISOString(),version:1};timeline.save(entry);log({actorId:input.authorId,actorRole:input.authorRole,action:input.type==='addendum'?'addendum':'create',resource:'timeline_entry',resourceId:entry.id,metadata:{recordId:input.medicalRecordId}});return entry}
export function revokeConsent(id:string,patientId:string){const value=consents.find(id);if(!value||value.patientId!==patientId)throw new Error('Autorização não encontrada.');consents.save({...value,revokedAt:new Date().toISOString()});log({actorId:patientId,actorRole:'patient',action:'revoke',resource:'record_consent',resourceId:id,metadata:{professionalId:value.professionalId}})}
export function listAuditLogs(){return audits.list()}
