import { useEffect, useState } from 'react'
import { Bot, Building2, MessageCircle, Play, RefreshCw, ShieldCheck, Users } from 'lucide-react'
import { getPlatformSummary, listAdminProspects, listResearchRuns, listResearchTargets, reviewAdminProspect, runProfessionalResearch, setResearchTargetEnabled, type ResearchRun, type ResearchTarget } from '../../lib/operations'

export function AdminUsers(){return <RealBackoffice title="Cadastros e pré-cadastros"/>}
export function AdminOperations(){return <RealBackoffice title="Central do backoffice"/>}

function RealBackoffice({title}:{title:string}){
  const [summary,setSummary]=useState<any>(null)
  const [prospects,setProspects]=useState<any[]>([])
  const [error,setError]=useState('')
  const [search,setSearch]=useState('')
  const [targets,setTargets]=useState<ResearchTarget[]>([])
  const [runs,setRuns]=useState<ResearchRun[]>([])
  const [busy,setBusy]=useState('')
  const [notice,setNotice]=useState('')
  async function load(){setError('');try{const [s,p,t,r]=await Promise.all([getPlatformSummary(),listAdminProspects(),listResearchTargets(),listResearchRuns()]);setSummary(s);setProspects(p);setTargets(t);setRuns(r)}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar backoffice.')}}
  useEffect(()=>{void load()},[])
  const visible=prospects.filter(p=>[p.name,p.primary_specialty,p.city,p.whatsapp].join(' ').toLowerCase().includes(search.toLowerCase()))
  async function review(id:string,status:'approved'|'rejected'|'duplicate',publish=false){try{await reviewAdminProspect(id,status,publish);await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao revisar pré-cadastro.')}}
  async function execute(action:'run'|'seed'){setBusy(action);setError('');setNotice('');try{const result=await runProfessionalResearch(action);setNotice(action==='seed'?`Fila atualizada: ${result.targets} combinações, ${result.cities} cidades e ${result.specialties} especialidades.`:`Lote concluído (${result.batchSize||1} alvos): ${result.fetched} encontrados, ${result.inserted} novos e ${result.updated} atualizados.`);await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao executar robô.')}finally{setBusy('')}}
  return <><div className="page-heading"><div><span className="badge">Administração geral</span><h1>{title}</h1><p className="muted">Dados reais de planos, organizações, pacientes e prospecção.</p></div><button className="btn btn-secondary" onClick={()=>void load()}><RefreshCw/> Atualizar</button></div>
    {error&&<div className="alert alert-error">{error}</div>}
    <div className="grid grid-4"><Metric icon={Building2} label="Organizações" value={String(summary?.organizations??0)}/><Metric icon={ShieldCheck} label="Planos ativos" value={String(summary?.active_organizations??0)}/><Metric icon={Users} label="Profissionais" value={String(summary?.professionals??0)}/><Metric icon={MessageCircle} label="Pré-cadastros" value={String(summary?.prospects??0)}/></div>
    {notice&&<div className="alert alert-success">{notice}</div>}
    <section className="card backoffice-table-card"><div className="section-heading"><div><span className="badge"><Bot/> Robô do diretório</span><h2>Pesquisa automática de profissionais</h2><p className="muted">A fila cobre as 200 maiores cidades e todas as especialidades ativas. Cada execução coleta todos os resultados encontrados para uma combinação, sem limite por cidade.</p></div><div className="row"><button className="btn btn-secondary" disabled={Boolean(busy)} onClick={()=>void execute('seed')}><RefreshCw/> {busy==='seed'?'Gerando...':'Atualizar fila nacional'}</button><button className="btn btn-primary" disabled={Boolean(busy)} onClick={()=>void execute('run')}><Play/> {busy==='run'?'Pesquisando...':'Executar próximo alvo'}</button></div></div><div className="grid grid-4"><Metric icon={Bot} label="Alvos carregados" value={String(targets.length)}/><Metric icon={ShieldCheck} label="Concluídos" value={String(targets.filter(t=>t.last_status==='completed').length)}/><Metric icon={Users} label="Encontrados na última rodada" value={String(targets.reduce((sum,t)=>sum+(t.last_result_count||0),0))}/><Metric icon={RefreshCw} label="Execuções registradas" value={String(runs.length)}/></div><div className="table-wrap"><table><thead><tr><th>Especialidade e cidade</th><th>Status</th><th>Resultado</th><th>Última execução</th><th>Ativo</th></tr></thead><tbody>{targets.slice(0,80).map(t=><tr key={t.id}><td><strong>{t.specialty}</strong><br/><small>{t.city}/{t.state_code}</small></td><td><span className="badge">{t.last_status||'aguardando'}</span></td><td>{t.last_result_count}</td><td>{t.last_run_at?new Date(t.last_run_at).toLocaleString('pt-BR'):'Ainda não executado'}</td><td><input aria-label={`Ativar ${t.specialty} em ${t.city}`} type="checkbox" checked={t.enabled} onChange={async e=>{await setResearchTargetEnabled(t.id,e.target.checked);await load()}}/></td></tr>)}</tbody></table></div></section>
    <section className="card backoffice-table-card"><div className="section-heading"><div><h2>Pré-cadastros pesquisados</h2><p className="muted">WhatsApp é privado e visível somente para a administração. Perfis básicos válidos são publicados automaticamente sem revelar contatos; a revisão manual continua disponível para rejeitar ou corrigir registros.</p></div><label className="search-field"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar nome, cidade ou especialidade"/></label></div><div className="table-wrap"><table><thead><tr><th>Nome</th><th>Especialidade</th><th>Cidade</th><th>WhatsApp privado</th><th>Revisão</th><th>Ações</th></tr></thead><tbody>{visible.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.primary_specialty}</td><td>{p.neighborhood&&`${p.neighborhood} · `}{p.city} - {p.state_code}</td><td>{p.whatsapp||'Não informado'}</td><td><span className="badge">{p.review_status} · {p.publication_status}</span></td><td><div className="row"><button className="btn btn-primary btn-small" onClick={()=>void review(p.id,'approved',true)}>Publicar</button><button className="btn btn-secondary btn-small" onClick={()=>void review(p.id,'rejected')}>Rejeitar</button></div></td></tr>)}</tbody></table></div>{!visible.length&&<div className="empty-state"><h3>Nenhum pré-cadastro real</h3><p className="muted">A pesquisa ainda não inseriu registros ou o filtro não encontrou resultados.</p></div>}</section>
  </>
}

function Metric({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <div className="card admin-metric"><div className="metric-icon"><Icon/></div><div><span className="muted">{label}</span><h2>{value}</h2></div></div>}
