import { useState } from 'react'
import {
  Activity, Bell, CheckCircle2, ClipboardList, CreditCard, FileClock, KeyRound, LifeBuoy,
  LockKeyhole, Mail, MessageCircle, MoreHorizontal, Plus, Search, Settings, ShieldCheck,
  SlidersHorizontal, UserCog, UserRound, Users, Webhook,
} from 'lucide-react'

const professionalRows = [
  ['Dra. Marina Lopes','Fonoaudiologia','Gestão Completa','Ativa','Verificada'],
  ['Paula Nascimento','Doula','Marketplace Gratuito','Ativa','Sem selo'],
  ['Ana Paula Mendes','Nutrição','Marketplace Gratuito','Em análise','Documentos pendentes'],
  ['Camila Rocha','Pediatria','Marketplace Ilimitado','Ativa','Verificada'],
]
const patientRows = [
  ['Camila Ribeiro','camila@email.com','Dra. Marina Lopes','Ativa','25/07/2026'],
  ['Juliana Martins','juliana@email.com','Dra. Marina Lopes','Ativa','26/07/2026'],
  ['Beatriz Lopes','beatriz@email.com','Camila Rocha','Ativa','27/07/2026'],
  ['Mariana Alves','mariana@email.com','Sem vínculo','Convite pendente','28/07/2026'],
]

export function AdminUsers(){
  const [tab,setTab]=useState<'professionals'|'patients'>('professionals')
  const [open,setOpen]=useState(false)
  const [saved,setSaved]=useState('')
  const title=tab==='professionals'?'profissional':'paciente'
  function submit(e:React.FormEvent){e.preventDefault();setSaved(`Nova ${title} cadastrada e convite de acesso enviado.`);setOpen(false)}
  return <><div className="page-heading"><div><span className="badge">Backoffice</span><h1>Cadastros e usuários</h1><p className="muted">Crie, localize e administre profissionais e pacientes da plataforma.</p></div><button className="btn btn-primary" onClick={()=>setOpen(true)}><Plus/> Cadastrar {title}</button></div>
    {saved&&<div className="success-banner"><CheckCircle2/>{saved}</div>}
    <div className="admin-user-tabs"><button className={tab==='professionals'?'active':''} onClick={()=>setTab('professionals')}><ShieldCheck/> Profissionais</button><button className={tab==='patients'?'active':''} onClick={()=>setTab('patients')}><Users/> Pacientes</button></div>
    <div className="grid grid-4"><Metric icon={Users} label={tab==='professionals'?'Profissionais':'Pacientes'} value={tab==='professionals'?'236':'1.842'}/><Metric icon={CheckCircle2} label="Ativos" value={tab==='professionals'?'218':'1.764'}/><Metric icon={FileClock} label="Pendentes" value={tab==='professionals'?'12':'48'}/><Metric icon={LockKeyhole} label="Bloqueados" value={tab==='professionals'?'6':'30'}/></div>
    <section className="card backoffice-table-card"><div className="admin-list-toolbar"><label className="search-field"><Search/><input placeholder={`Buscar ${title} por nome, e-mail ou documento`}/></label><button className="btn btn-secondary"><SlidersHorizontal/> Filtros</button><button className="btn btn-secondary">Exportar</button></div>
      <div className="table-wrap"><table><thead><tr>{(tab==='professionals'?['Profissional','Especialidade','Plano','Status','Verificação']:['Paciente','E-mail','Profissional vinculada','Status','Cadastro']).map(x=><th key={x}>{x}</th>)}<th>Ações</th></tr></thead><tbody>{(tab==='professionals'?professionalRows:patientRows).map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{j===3?<span className="badge">{cell}</span>:cell}</td>)}<td><button className="icon-btn"><MoreHorizontal/></button></td></tr>)}</tbody></table></div>
    </section>
    {open&&<div className="modal-backdrop"><form className="modal-card admin-create-modal" onSubmit={submit}><div className="modal-head"><div><span className="badge">Cadastro administrativo</span><h2>Nova {title}</h2><p className="muted">Crie o registro e envie o acesso inicial por e-mail ou WhatsApp.</p></div><button type="button" className="icon-btn" onClick={()=>setOpen(false)}>×</button></div><div className="form-grid"><label className="field field-span-2"><span>Nome completo</span><input required/></label><label className="field"><span>E-mail</span><input type="email" required/></label><label className="field"><span>WhatsApp</span><input required/></label>{tab==='professionals'?<><label className="field"><span>Especialidade</span><select><option>Fonoaudiologia</option><option>Pediatria</option><option>Psicologia perinatal</option><option>Nutrição</option><option>Doula</option></select></label><label className="field"><span>Plano inicial</span><select><option>Marketplace Gratuito</option><option>Marketplace Ilimitado</option><option>Gestão Completa</option></select></label><label className="field"><span>Registro profissional</span><input/></label><label className="field"><span>Cidade</span><input/></label></>:<><label className="field"><span>CPF</span><input/></label><label className="field"><span>Data de nascimento</span><input type="date"/></label><label className="field field-span-2"><span>Profissional vinculada</span><select><option>Sem vínculo</option><option>Dra. Marina Lopes</option><option>Camila Rocha</option></select></label></>}</div><label className="check-row"><input type="checkbox" defaultChecked/><span>Enviar convite para criação de senha após salvar.</span></label><div className="modal-actions"><button type="button" className="btn btn-secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn btn-primary">Cadastrar e enviar convite</button></div></form></div>}
  </>
}

type OpsTab='subscriptions'|'support'|'access'|'audit'|'integrations'
export function AdminOperations(){
  const [tab,setTab]=useState<OpsTab>('subscriptions')
  const tabs:[OpsTab,string,any][]=[['subscriptions','Planos e assinaturas',CreditCard],['support','Atendimento e suporte',LifeBuoy],['access','Equipe e permissões',KeyRound],['audit','Auditoria',ClipboardList],['integrations','Integrações',Webhook]]
  return <><div className="page-heading"><div><span className="badge">Operação administrativa</span><h1>Central do backoffice</h1><p className="muted">Governança, suporte, acessos, assinaturas e integrações em um só lugar.</p></div><button className="btn btn-secondary"><Settings/> Configurações gerais</button></div>
    <div className="backoffice-nav">{tabs.map(([id,label,Icon])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><Icon/>{label}</button>)}</div>
    {tab==='subscriptions'&&<Subscriptions/>}{tab==='support'&&<Support/>}{tab==='access'&&<Access/>}{tab==='audit'&&<Audit/>}{tab==='integrations'&&<Integrations/>}
  </>
}

function Subscriptions(){return <><div className="grid grid-4"><Metric icon={CreditCard} label="Assinaturas ativas" value="194"/><Metric icon={Activity} label="Receita recorrente" value="R$ 21.480"/><Metric icon={FileClock} label="Inadimplentes" value="9"/><Metric icon={Bell} label="Renovações em 7 dias" value="26"/></div><section className="card backoffice-table-card"><h2>Gestão de planos</h2><div className="table-wrap"><table><thead><tr><th>Profissional</th><th>Plano</th><th>Valor</th><th>Próxima cobrança</th><th>Status</th><th>Ação</th></tr></thead><tbody>{[['Marina Lopes','Gestão Completa','R$ 159,90','05/08/2026','Ativa'],['Camila Rocha','Marketplace Ilimitado','R$ 29,90','07/08/2026','Ativa'],['Fernanda Alves','Gestão Completa','R$ 159,90','08/08/2026','Pagamento pendente']].map(r=><tr key={r[0]}>{r.map((x,i)=><td key={x}>{i===4?<span className="badge">{x}</span>:x}</td>)}<td><button className="btn btn-secondary btn-small">Gerenciar</button></td></tr>)}</tbody></table></div></section></>}
function Support(){return <div className="grid grid-2"><section className="card"><div className="section-heading"><h2>Fila de atendimento</h2><span className="badge">5 abertos</span></div>{[['#1048','Erro ao atualizar perfil','Alta'],['#1047','Dúvida sobre cobrança','Média'],['#1046','Alteração de convênio','Normal']].map(r=><div className="support-ticket" key={r[0]}><span><strong>{r[0]} · {r[1]}</strong><small>Aberto há 32 minutos</small></span><em>{r[2]}</em><button className="btn btn-secondary btn-small">Atender</button></div>)}</section><section className="card"><h2>Canais</h2>{[[Mail,'E-mail','12 aguardando'],[MessageCircle,'WhatsApp','7 aguardando'],[LifeBuoy,'Central de ajuda','86% resolvidos']].map(([Icon,name,note]:any)=><div className="list-item" key={name}><span className="row"><Icon/><b>{name}</b></span><strong>{note}</strong></div>)}</section></div>}
function Access(){return <><div className="grid grid-3"><Metric icon={UserCog} label="Administradores" value="3"/><Metric icon={LifeBuoy} label="Equipe de suporte" value="5"/><Metric icon={ShieldCheck} label="Perfis de acesso" value="4"/></div><section className="card backoffice-table-card"><div className="section-heading"><div><h2>Equipe administrativa</h2><p className="muted">Controle de acesso por função e princípio do menor privilégio.</p></div><button className="btn btn-primary"><Plus/> Convidar integrante</button></div>{[['Jéssica Calegari','Superadministradora','Acesso total'],['Fernanda Lima','Suporte','Cadastros e chamados'],['Rafael Souza','Financeiro','Cobranças e repasses']].map(r=><div className="admin-team-row" key={r[0]}><div className="avatar"><UserRound/></div><span><strong>{r[0]}</strong><small>{r[1]}</small></span><em>{r[2]}</em><button className="icon-btn"><MoreHorizontal/></button></div>)}</section></>}
function Audit(){return <section className="card backoffice-table-card"><div className="section-heading"><div><h2>Trilha de auditoria</h2><p className="muted">Registro de ações sensíveis realizadas no backoffice.</p></div><button className="btn btn-secondary">Exportar logs</button></div>{[['15:42','Jéssica Calegari','Aprovou cadastro profissional','Ana Paula Mendes'],['14:18','Sistema','Renovou assinatura','Marina Lopes'],['12:06','Fernanda Lima','Alterou telefone da paciente','Juliana Martins'],['10:31','Rafael Souza','Aprovou reembolso','Pagamento #8492']].map(r=><div className="audit-row" key={r.join()}><FileClock/><strong>{r[0]}</strong><span><b>{r[1]}</b><small>{r[2]} · {r[3]}</small></span><button className="btn btn-secondary btn-small">Detalhes</button></div>)}</section>}
function Integrations(){return <div className="grid grid-2">{[[MessageCircle,'WhatsApp Business','Conectado','Mensagens, lembretes e suporte'],[CreditCard,'Asaas','Modo demonstração','Pagamentos, assinaturas e webhooks'],[Mail,'E-mail transacional','Conectado','Convites, redefinição de senha e alertas'],[Webhook,'Videoconferência','Pendente','Salas seguras para teleconsultas']].map(([Icon,name,status,copy]:any)=><article className="card integration-admin-card" key={name}><div className="metric-icon"><Icon/></div><span><h3>{name}</h3><p className="muted">{copy}</p></span><em>{status}</em><button className="btn btn-secondary">Configurar</button></article>)}</div>}
function Metric({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <div className="card admin-metric"><div className="metric-icon"><Icon/></div><div><span className="muted">{label}</span><h2>{value}</h2></div></div>}
